apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/maron-gt123/k8s-setup-for-proxmox
        revision: main
        directories:
          - path: k8s/manifests/apps/cluster-wide-app/*
  template:
    metadata:
      # 各Application が argocd namespace に配置されるため prefix した方が安全
      name: "cluster-wide-apps-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: cluster-wide-apps
      source:
        repoURL: https://github.com/maron-gt123/k8s-setup-for-proxmox
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "cluster-wide-apps"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
