apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maron-gt123/k8s-setup-for-proxmox.git
    targetRevision: main
    path: k8s/manifests/apps/cluster-wide-apps/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
