apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mic-lobby-sv
  name: primary-sv
  labels:
    app: primary-sv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary-sv
  template:
    metadata:
      labels:
        app: primary-sv
    spec:
      containers:
        - name: primary-sv
          image: noevidenz/multipaper-master:edge
          env:
            - name: TZ
              value: Asia/Tokyo
          resources:
            requests:
              memory: 2G
              cpu: "2"
          ports:
            - name: multipaper-external-port
              containerPort: 25565
            - name: multipaper-internal-port
              containerPort: 35353
          volumeMounts:
            - name: primary-sv-storage
              mountPath: /app
      volumes:
        - name: primary-sv-storage
          persistentVolumeClaim:
            claimName: primary-sv-pvc
