apiVersion: v1
kind: Namespace
metadata:
  name: mic-lobby-sv
  labels:
    name: mic-lobby-sv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mic-lobby-sv
  name: primary-sv
  labels:
    app: primary-sv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary-sv
  template:
    metadata:
      labels:
        app: primary-sv
    spec:
      containers:
        - name: primary-sv
          image: akiicat/multipaper-master:java21
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
          resources:
            limits:
              memory: 2048Mi
              cpu: 1000m
            requests:
              memory: 2048Mi
              cpu: 1000m
          ports:
            - name: primary-sv
              containerPort: 35353
