apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mic-lobby-sv
  name: multi-lobby-sv
  labels:
    app: multi-lobby-sv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-lobby-sv
  template:
    metadata:
      labels:
        app: multi-lobby-sv
    spec:
      containers:
        - image: noevidenz/multipaper:edge
          name: multi-lobby-sv
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx1G -DmultipaperMasterAddress=0.0.0.0:35353"
          ports:
            - name: multi-lobby-sv
              containerPort: 25565
          resources:
            requests:
              memory: 2Gi
              cpu: "2"
#          volumeMounts:
#            - name: multipaper-configs
#              mountPath: /app/multipaper.yml
#              subPath: multipaper.yml
#      volumes:
#        - name: multipaper-configs
#          configMap:
#            name: multipaper-configs
