apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mic-lobby-sv
  name: multi-lobby-sv
  labels:
    app: multi-lobby-sv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-lobby-sv
  template:
    metadata:
      labels:
        app: multi-lobby-sv
    spec:
      containers:
        - image: noevidenz/multipaper:edge
          name: multi-lobby-sv
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx1G -DmultipaperMasterAddress=primary-sv-ex-service:35353"
            - name: PLUGINS
              value: >-
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar,
                https://download.luckperms.net/1549/bukkit/loader/LuckPerms-Bukkit-5.4.134.jar
          ports:
            - name: multi-lobby-sv
              containerPort: 25565
          resources:
            requests:
              memory: 2Gi
              cpu: "2"
