apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multipaper-configs-pvc
  namespace: mic-lobby-sv
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
