apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mic-lobby-sv
  name: multipaper-configs-pvc
  labels: 
    app: multipaper-configs-pvc
spec:
  storageClassName: nfs-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
