#kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 45.7.1
      values:
        - $myRepo/k8s/apps/cluster-wide-apps/prometheus/values/kube-prometheus-stack.yaml
    - repoURL: 'https://github.com/maron-gt123/k8s-setup-for-proxmox.git'
      targetRevision: HEAD
      ref: myRepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated: {}
