apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 45.25.0
      helm:
      releaseName: prometheus
      skipCrds: true
      values: 
        - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/apps/cluster-wide-apps/prometheus/values.yaml
#        valueFiles:
#          - main/k8s/apps/cluster-wide-apps/prometheus/values.yaml
#    - repoURL: 'https://github.com/maron-gt123/k8s-setup-for-proxmox.git'
#      targetRevision: HEAD
#      ref: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
