project: default
source:
  repoURL: 'https://prometheus-community.github.io/helm-charts'
  targetRevision: 16.11.0
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: prometheusOperator.admissionWebhooks.failurePolicy
        value: Ignore
  chart: kube-prometheus-stack
destination:
  server: 'https://kubernetes.default.svc'
  namespace: prometheus-community
syncPolicy:
  syncOptions:
    - CreateNamespace=true
