apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: prometheus
  name: prometheus-pv
  labels:
    app: prometheus
spec:
  storageClassName: prometheus
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  nfs:
    server: 192.168.6.53
    path: /kubanetesu-NFS/prometheus/
  persistentVolumeReclaimPolicy: Delete
