apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: kube-prometheus-stack-prometheus
  type: LoadBalancer
  loadBalancerIP: 192.168.15.64
