apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: prometheus-pv
  labels:
    app: prometheus
spec:
  storageClassName: prometheus
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/prometheus/
  persistentVolumeReclaimPolicy: Recycle
