apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: proxy-sv
  name: proxy-metrics
  labels:
    app: proxy
    release: prometheus
spec:
  endpoints:
    - interval: 30s
      port: jmx-metrics
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: proxy
      role: metrics
---
apiVersion: v1
kind: Service
metadata:
  namespace: proxy-sv
  name: proxy-metrics
  labels:
    app: proxy
    role: metrics
spec:
  type: ClusterIP
  ports:
    - name: jmx-metrics
      port: 18321
      protocol: TCP
      targetPort: jmx-metrics
    - name: metrics
      port: 9225
      protocol: TCP
      targetPort: metrics
  selector:
    app: proxy
