apiVersion: v1
kind: Service
metadata:
  name: proxy-lb
  labels:
    app: "$(APP_NAME)"
spec:
  type: LoadBalancer
  ports:
    - name: proxy-service
      port: 53616
      protocol: TCP
      targetPort: "$(APP_NAME)"
  selector:
    app: "$(APP_NAME)"
  loadBalancerIP: 192.168.15.70
