apiVersion: v1
kind: Service
metadata:
  namespace: proxy-sv
  name: proxy-lb
  labels:
    app: proxy
spec:
  type: LoadBalancer
  ports:
    - name: service
      port: 53616
      protocol: TCP
      targetPort: proxy
  selector:
    app: proxy
  loadBalancerIP: 192.168.15.70
