apiVersion: v1
kind: Service
metadata:
  name: mc-proxy-lb
  labels:
    app: mc-proxy
spec:
  type: LoadBalancer
  ports:
    - name: proxy-service
      port: 53616
      protocol: TCP
      targetPort: mc-proxy
  selector:
    app: mc-proxy
  loadBalancerIP: "$(VIP_IP_ADDRESS)"
