defaultRules:
  create: true
  rules:
    kubeProxy: false
    alertmanager: false
grafana:
  enabled: false
  namespaceOverride: ""

  ## ForceDeployDatasources Create datasource configmap even if grafana deployment has been disabled
  ##
  forceDeployDatasources: false

  ## ForceDeployDashboard Create dashboard configmap even if grafana deployment has been disabled
  ##
  forceDeployDashboards: false

  ## Deploy default dashboards
  ##
  defaultDashboardsEnabled: true

  ## Timezone for the default dashboards
  ## Other options are: browser or a specific timezone, i.e. Europe/Luxembourg
  ##
  defaultDashboardsTimezone: jp
prometheus:
  prometheusSpec:
    additionalScrapeConfigs: 
      - job_name: "prometheus"
        static_configs:
        - targets: ["localhost:9090"]
alertmanager:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: true
  endpoints:
    - 192.168.15.81
    - 192.168.15.82
    - 192.168.15.83
  service:
    enabled: true
    port: 2381
    targetPort: 2381
