defaultRules:
  create: true
  rules:
    kubeProxy: false
    alertmanager: false
grafana:
  enabled: false
prometheus:
  prometheusSpec:
    additionalScrapeConfigs: 
      - job_name: "prometheus"
        static_configs:
        - targets: ["localhost:9090"]
alertmanager:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: true
  endpoints:
    - 192.168.15.81
    - 192.168.15.82
    - 192.168.15.83
  service:
    enabled: true
    port: 2381
    targetPort: 2381
