defaultRules:
  create: true
  rules:
  kubeProxy: false
grafana:
  enabled: true
  namespaceOverride: ""
  defaultDashboardsTimezone: Asia/Tokyo
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: true
  endpoints:
    - 192.168.15.81
    - 192.168.15.82
    - 192.168.15.83
  service:
    enabled: true
    port: 2381
    targetPort: 2381
prometheusSpec:
  additionalScrapeConfigs: 
    - job_name: 'minecraft-loby-SV'
      static_configs:
        - targets: ['lobbySV.micnet:9225']
    - job_name: 'minecraft-paper01-SV'
      static_configs:
        - targets: ['paper01.micnet:9225']
