defaultRules:
  create: true
  rules:
    kubeProxy: false
grafana:
  defaultDashboardsTimezone: Asia/Tokyo
kubeProxy:
  enabled: false
kubeEtcd:
  endpoints:
  - 192.168.6.81
  - 192.168.6.82
  - 192.168.6.83
service:
  enabled: true
  port: 2381
  targetPort: 2381
