apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-app
  namespace: argocd
spec:
  project: default
  source:
    helm:
      name: kube-prometheus-stack
      version: 46.8.0
      repository: https://prometheus-community.github.io/helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
