apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.26.0
    helm:
      releaseName: prometheus
      skipCrds: true
      values: |
        defaultRules:
          create: true
          rules:
            kubeProxy: false
        grafana:
          defaultDashboardsTimezone: Asia/Tokyo
        kubeProxy:
          enabled: false
        kubeEtcd:
          endpoints:
            - 192.168.18.11
            - 192.168.18.12
            - 192.168.18.13
          service:
            enabled: true
            port: 2381
            targetPort: 2381
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
