apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: prometheus-pv
spec:
  storageClassName: prometheus-nsf
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: nas.storagenet
    path: /kubanetesu-NFS/prometheus/
  persistentVolumeReclaimPolicy: Recycle
