apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: monitoring
spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
　  app.kubernetes.io/instance: prometheus-kube-prometheus-prometheus
  type: LoadBalancer
  loadBalancerIP: 192.168.15.64
