apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  source:
    chart: prometheus-blackbox-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 7.10.0
    helm:
      releaseName: prometheus-blackbox-exporter
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml
      values: |
        config:
          modules:
            http_2xx:
              prober: http
            http_2xx_insecure:
              prober: http
              http:
                tls_config:
                  insecure_skip_verify: true
            http_post_2xx:
              prober: http
              http:
                method: POST
            tcp_connect:
              prober: tcp
            pop3s_banner:
              prober: tcp
              tcp:
                query_response:
                - expect: "^+OK"
                tls: true
                tls_config:
                  insecure_skip_verify: false
            grpc:
              prober: grpc
              grpc:
                tls: true
                preferred_ip_protocol: "ip4"
            grpc_plain:
              prober: grpc
              grpc:
                tls: false
                service: "service1"
            ssh_banner:
              prober: tcp
              tcp:
                query_response:
                - expect: "^SSH-2.0-"
                - send: "SSH-2.0-blackbox-ssh-check"
            irc_banner:
              prober: tcp
              tcp:
                query_response:
                - send: "NICK prober"
                - send: "USER prober prober prober :prober"
                - expect: "PING :([^ ]+)"
                  send: "PONG ${1}"
                - expect: "^:[^ ]+ 001"
            dns:
              prober: dns
            icmp:
              prober: icmp
              icmp:
                source_ip_address: 127.0.0.1
            icmp_v4:
              prober: icmp
              icmp:
                preferred_ip_protocol: ip4
                source_ip_address: 127.0.0.1
            icmp_v6:
              prober: icmp
              icmp:
                preferred_ip_protocol: ip6
                source_ip_address: 127.0.0.1
            icmp_jumbo:
              prober: icmp
              icmp:
                dont_fragment: true
                payload_size: 8972
                source_ip_address: 127.0.0.1
            icmp_ttl5:
              prober: icmp
              timeout: 5s
              icmp:
                ttl: 5
                source_ip_address: 127.0.0.1
        serviceMonitor:
          enabled: true
          defaults:
            labels:
              release: prometheus
            interval: 5s
            scrapeTimeout: 5s
          targets:
            - name: onp-nas-service
              url: nas.micnet
              module: icmp_v4
            - name: onp-prox01-service
              url: prox01.micnet
              module: icmp_v4
            - name: onp-prox02-service
              url: prox02.micnet
              module: icmp_v4
            - name: onp-prox03-service
              url: prox03.micnet
              module: icmp_v4  
            - name: onp-nas-storage
              url: 192.168.6.140
              module: icmp_v4
            - name: onp-prox01-storage
              url: 192.168.6.141
              module: icmp_v4
            - name: onp-prox02-storage
              url: 192.168.6.142
              module: icmp_v4
            - name: onp-prox03-storage
              url: 192.168.6.143
              module: icmp_v4
            - name: onp-prox01-service-web-panel
              url: https://prox01.micnet:8006
              module: http_2xx_insecure
            - name: onp-prox02-service-web-panel
              url: https://prox02.micnet:8006
              module: http_2xx_insecure
            - name: onp-prox03-service-web-panel
              url: https://prox03.micnet:8006
              module: http_2xx_insecure
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
