apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-snmp-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  source:
    chart: prometheus-snmp-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 1.8.0
    helm:
      releaseName: prometheus-snmp-exporter
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-snmp-exporter/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
