# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
#kube-prometheus-stack-CRD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-46.3.0
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
#kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 46.8.0
      helm:
        releaseName: prometheus
        skipCrds: true
        values: |
          defaultRules:
            create: true
            rules:
              kubeProxy: false
              alertmanager: false
          grafana:
            enabled: true
          prometheus:
            prometheusSpec:
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: prometheus-nsf
                    accessModes: ["ReadWriteMany"]
                    resources:
                      requests:
                        storage: 10Gi
              resources:
                requests:
                  memory: 2Gi
              retention: 60d
          alertmanager:
            enabled: false
          kubeProxy:
            enabled: false
          kubeEtcd:
            endpoints:
              - 192.168.6.81
              - 192.168.6.82
              - 192.168.6.83
            service:
              enabled: true
              port: 2381
              targetPort: 2381
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
