# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
#kube-prometheus-stack-CRD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/charts/crds/
    targetRevision: kube-prometheus-stack-48.0.0
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - Replace=true
---
#kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 48.3.2
      helm:
        releaseName: prometheus
        skipCrds: true
        values: |
          defaultRules:
            create: true
            rules:
              kubeProxy: false
              alertmanager: false
          loki:
            isDefault: false
          grafana:
            enabled: true
            sidecar:
              datasources:
                defaultDatasourceEnabled: false
                isDefaultDatasource: false
            defaultDashboardsTimezone: Asia/Tokyo
            plugins:
              - grafana-piechart-panel
              - isovalent-hubble-datasource
              - grafana-sentry-datasource
            deploymentStrategy:
              type: Recreate
            persistence:
              enabled: true
              size: 10Gi
            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                  - name: Prometheus
                    type: prometheus
                    url: http://prometheus-kube-prometheus-prometheus:9090
                    isDefault: true
                  - name: Loki
                    type: Loki
                    url: http://loki:3100
                    isDefault: false
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                  - name: 'default'
                    orgId: 1
                    folder: ''
                    type: file
                    allowUiUpdates: true
                    disableDeletion: true
                    editable: false
                    options:
                      path: /var/lib/grafana/dashboards/default
            dashboards:
              default:
                cilium-agent:
                  gnetId: 16611
                  revision: 1
                  datasource: Prometheus
                cilium-operator:
                  gnetId: 16612
                  revision: 1
                  datasource: Prometheus
                cilium-hubble:
                  gnetId: 16613
                  revision: 1
                  datasource: Prometheus
                cilium-verdicts:
                  gnetId: 18015
                  revision: 3
                  datasource: Prometheus
                argocd:
                  gnetId: 14584
                  revision: 1
                node-exporter:
                  gnetId: 1860
                  revision: 31
          prometheus:
            prometheusSpec:
              additionalScrapeConfigs: 
                - job_name: 'prometheus'
                  static_configs:
                    - targets: ['localhost:9090']
                - job_name: 'node exporter'
                  static_configs:
                    - targets: ['192.168.15.131:9100']
                      labels:
                        server_name: 'sql-server'
                    - targets: ['192.168.15.130:9100']
                      labels:
                        server_name: 'ssh-server'
                    - targets: ['192.168.15.140:9100']
                      labels:
                        server_name: 'nas-server'
                    - targets: ['192.168.15.81:9100']
                      labels:
                        server_name: 'k8s-cp1-server'
                    - targets: ['192.168.15.82:9100']
                      labels:
                        server_name: 'k8s-cp2-server'
                    - targets: ['192.168.15.83:9100']
                      labels:
                        server_name: 'k8s-cp3-server'
                    - targets: ['192.168.15.84:9100']
                      labels:
                        server_name: 'k8s-wk1-server'
                    - targets: ['192.168.15.85:9100']
                      labels:
                        server_name: 'k8s-wk2-server'
                    - targets: ['192.168.15.86:9100']
                      labels:
                        server_name: 'k8s-wk3-server'
                - job_name: 'minecraft'
                  static_configs:
                    - targets: ['192.168.15.87:9225']
                      labels:
                        server_name: 'minecraft-server-lobby'
                    - targets: ['192.168.15.88:9225']
                      labels:
                        server_name: 'minecraft-server-S1'
                    - targets: ['192.168.15.89:9225']
                      labels:
                        server_name: 'minecraft-server-S2'
                    - targets: ['192.168.15.71:9225']
                      labels:
                        server_name: 'minecraft-server-k8s'
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    resources:
                      requests:
                        storage: 10Gi
              resources:
                requests:
                  memory: 2Gi
              retention: 60d
          alertmanager:
            enabled: false
          kubeProxy:
            enabled: false
          kubeEtcd:
            endpoints:
              - 192.168.6.81
              - 192.168.6.82
              - 192.168.6.83
            service:
              enabled: true
              port: 2381
              targetPort: 2381
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
