# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
#kube-prometheus-stack-CRD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-47.0.0
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
#kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 47.0.0
      helm:
        releaseName: prometheus
        skipCrds: true
        values: |
          defaultRules:
            create: true
            rules:
              kubeProxy: false
              alertmanager: false
          grafana:
            enabled: true
            sidecar:
              datasources:
                defaultDatasourceEnabled: false
            defaultDashboardsTimezone: Asia/Tokyo
            plugins:
              - grafana-piechart-panel
              - isovalent-hubble-datasource
            deploymentStrategy:
              type: Recreate
            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                  - name: Prometheus
                    type: prometheus
                    url: http://prometheus-kube-prometheus-prometheus:9090
                    isDefault: true
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                  - name: 'default'
                    orgId: 1
                    folder: ''
                    type: file
                    allowUiUpdates: true
                    disableDeletion: true
                    editable: false
                    options:
                      path: /var/lib/grafana/dashboards/default
            dashboards:
              default:
                cilium-agent:
                  gnetId: 16611
                  revision: 1
                  datasource: Prometheus
                cilium-operator:
                  gnetId: 16612
                  revision: 1
                  datasource: Prometheus
                cilium-hubble:
                  gnetId: 16613
                  revision: 1
                  datasource: Prometheus
                cilium-verdicts:
                  gnetId: 18015
                  revision: 3
                  datasource: Prometheus
                argocd:
                  gnetId: 14584
                  revision: 1
          prometheus:
            prometheusSpec:
              additionalScrapeConfigs: 
                - job_name: 'prometheus'
                  static_configs:
                    - targets: ['localhost:9090']
                - job_name: 'minecraft'
                  static_configs:
                    - targets: ['mic-lobby.micnet:9225']
                      labels:
                        server_name: 'minecraft-server-lobby'
                    - targets: ['mic-paper01.micnet:9225']
                      labels:
                        server_name: 'minecraft-server-S1'
                    - targets: ['192.168.15.71:9225']
                      labels:
                        server_name: 'minecraft-server-k8s'
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: prometheus-nsf
                    accessModes: ["ReadWriteMany"]
                    resources:
                      requests:
                        storage: 10Gi
              resources:
                requests:
                  memory: 2Gi
              retention: 60d
          alertmanager:
            enabled: false
          kubeProxy:
            enabled: false
          kubeEtcd:
            service:
              enabled: true
              port: 2381
              targetPort: 2381
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
