# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
#kube-prometheus-stack-CRD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-46.3.0
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
#kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 46.8.0
      helm:
        releaseName: prometheus
        skipCrds: true
        values: |
          defaultRules:
            create: true
            rules:
              kubeProxy: false
              alertmanager: false
          grafana:
            enabled: true
            defaultDashboardsTimezone: Asia/Tokyo
            dashboards:
              default:
                cilium-agent:
                  gnetId: 16611
                  revision: 1
                  datasource: Prometheus
                cilium-operator:
                  gnetId: 16612
                  revision: 1
                  datasource: Prometheus
                cilium-hubble:
                  gnetId: 16613
                  revision: 1
                  datasource: Prometheus
                cilium-verdicts:
                  gnetId: 18015
                  revision: 3
                  datasource: Prometheus
                argocd:
                  gnetId: 14584
                  revision: 1
          prometheus:
            prometheusSpec:
              additionalScrapeConfigs: 
                - job_name: 'prometheus'
                  static_configs:
                    - targets: ['localhost:9090']
                - job_name: 'bungeecord'
                  static_configs:
                    - targets: ['192.168.15.70:9225']
                      labels:
                        proxy_name: 'minecraft-proxy'
                - job_name: 'minecraft'
                  static_configs:
                    - targets: ['mic-lobby.micnet:9225']
                      labels: 
                        server_name: 'minecraft-lobby-server'
                    - targets: ['mic-paper01.micnet:9225']
                      labels: 
                        server_name: 'minecraft-S1-server'
                    - targets: ['mic-paper02.micnet:9225']
                      labels: 
                        server_name: 'minecraft-S2-server'
              secrets:
                - etcd-client
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: prometheus-nsf
                    accessModes: ["ReadWriteMany"]
                    resources:
                      requests:
                        storage: 10Gi
              resources:
                requests:
                  memory: 2Gi
              retention: 60d
          alertmanager:
            enabled: false
          kubeProxy:
            enabled: false
          kubeEtcd:
            endpoints:
              - 192.168.15.81
              - 192.168.15.82
              - 192.168.15.83
            service:
              enabled: true
              port: 2379
              targetPort: 2379
            serviceMonitor:
              scheme: https
              insecureSkipVerify: true
              caFile: /etc/kubernetes/pki/etcd/ca.crt
              certFile: /etc/kubernetes/pki/etcd/client.crt
              keyFile: /etc/kubernetes/pki/etcd/client.key
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
