apiVersion: v1
kind: Service
metadata:
  name: snmp-ex-lb
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9116
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.15.66
