apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-snmp-exporter
  name: snmp-ex-lb
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9116
  selector:
    app.kubernetes.io/instance: prometheus-snmp-exporter
    app.kubernetes.io/name: prometheus-snmp-exporter
  type: LoadBalancer
  loadBalancerIP: 192.168.15.66
