apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-tohoku-sv
resources:
  # namespace
  - ./ns-mc-tohoku-sv.yaml
  # template
  - ../templates/minecraft-server
  # advancedportals
  - ./mc-plugin-advancedportals-configs.yaml
  # holograms
  - ./mc-plugin-holograms-configs.yaml

patches:
  - path: mc-tohoku-configs.yaml
  - path: tohoku-statefulset.yaml
