apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-tohoku-sv
resources:
  # namespace
  - ./ns-mc-tohoku-sv.yaml
  # template
  - ../templates/minecraft-server
  # pv
  - ./nsf-pv-mc-tohoku.yaml
  # pvc
  - ./nsf-pvc-mc-tohoku.yaml
  
patches:
  - path: tohoku-statefulset.yaml
  - path: mc-tohoku-plugin-advancedportals-configs.yaml
