apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-destinations-config
data:
  Advanced-destinations.yml: 
    #  ExampleDestination:
    #    world: it will be the world name
    #    pos:
    #      X:
    #      Y:
    #      Z:
