apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-tohoku-pvc
  labels:
    app: mc-tohoku
spec:
  storageClassName: mc-tohoku-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
