apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-tohoku-world-pv
  labels:
    app: mc-tohoku
spec:
  storageClassName: mc-tohoku-world-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/mc-tohoku/world/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-tohoku-nether-pv
  labels:
    app: mc-tohoku
spec:
  storageClassName: mc-tohoku-nether-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/mc-tohoku/world_nether
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-tohoku-end-pv
  labels:
    app: mc-tohoku
spec:
  storageClassName: mc-tohoku-end-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/mc-tohoku/world_the_end
  persistentVolumeReclaimPolicy: Retain
