apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          env:
            # ------tohoku用の変数設定 ------
            # ------LuckPermsのサーバー名 ------
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: tohoku
            - name: SPIGET_RESOURCES
              # 7849:mysql-inventory-bridge
              value: "7849"
          volumeMounts:
            - name: world-data
              mountPath: /data/world
            - name: nether-data
              mountPath: /data/world_nether
            - name: end-data
              mountPath: /data/world_the_end
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: mc-tohoku-world-pvc
        # netherデータの永続ストレージの指定
        - name: nether-data
          persistentVolumeClaim:
            claimName: mc-tohoku-nether-pvc
        # netherデータの永続ストレージの指定
        - name: end-data
          persistentVolumeClaim:
            claimName: mc-tohoku-end-pvc
