apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          env:
            # ------tohoku用の変数設定 ------
            # ------LuckPermsのサーバー名 ------
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: tohoku
            - name: SPIGET_RESOURCES
              # 7849:mysql-inventory-bridge
              value: 7849
          volumeMounts:
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ MysqlInventoryBridge ------
            - name: init-download-volume
              mountPath: /data/plugins/MysqlInventoryBridge.jar
              subPath: MysqlInventoryBridge.jar
      volumes:
        # minecraft-musicサーバーの永続ストレージの指定
        - name: data
          persistentVolumeClaim:
            claimName: mc-tohoku-pvc
