apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: MYSQLINVENTORYBRIDGE_URL
              value: "https://www.spigotmc.org/resources/mysql-inventory-bridge.7849/download?version=357227"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/MysqlInventoryBridge.jar "${MYSQLINVENTORYBRIDGE_URL}"
      containers:
        - name: minecraft
          env:
            # ------tohoku用の変数設定 ------
            # ------LuckPermsのサーバー名 ------
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: tohoku
          volumeMounts:
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ MysqlInventoryBridge ------
            - name: init-download-volume
              mountPath: /data/plugins/MysqlInventoryBridge.jar
              subPath: MysqlInventoryBridge.jar
            # ------tohoku用configファイルマウント ------
            # ------AdvancedPortalsの各ゲート座標ファイルマウント ------
            - name: ad-destinations-config
              mountPath: /plugins/AdvancedPortals/destinations.yml
              subPath: Advanced-destinations.yml
      volumes:
        # minecraft-musicサーバーの永続ストレージの指定
        - name: data
          persistentVolumeClaim:
            claimName: mc-tohoku-pvc
