apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # deployment
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/deployment.yaml
  # service
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/refs/heads/main/k8s/manifests/apps/templates/minecraft-proxy/service-LoadBalancer.yaml
  # metrics-service
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/refs/heads/main/k8s/manifests/apps/templates/minecraft-proxy/metrics-patch.yaml
  # jmx-exporter-config
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/jmx-exporter-config.yaml
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml
patches:
  # deployment.yamlのmanifest編集
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
    patch: |-
      - op: replace
        path: /metadata/name
        value: velocity
      - op: replace
        path: /metadata/labels/app
        value: velocity
      - op: replace
        path: /spec/selector/matchLabels/app
        value: velocity
      - op: replace
        path: /spec/template/metadata/labels/app
        value: velocity
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1024Mi
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: velocity
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: 1024m
