apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # template
  - ../templates/minecraft-proxy
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml

configMapGenerator:
  - name: external-env
    envs:
      - external.env

patches:
  - target:
      kind: Service
      name: mc-proxy-lb
    patch: |-
      - op: replace
        path: /spec/loadBalancerIP
        valueFrom:
          configMapKeyRef:
            name: external-env
            key: LOAD_BALANCER_IP
  - target:
      kind: Deployment
      name: mc-proxy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        valueFrom:
          configMapKeyRef:
            name: external-env
            key: MEMORY_REQUEST
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        valueFrom:
          configMapKeyRef:
            name: external-env
            key: RESOURCE_PROXY_MEMORY
