apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # template
  - ../templates/minecraft-proxy
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml
  # params
  - ./params.yaml
configMapGenerator:
  - name: params-config
    behavior: merge
    envs:
      - params.yaml
vars:
  - name: VIP_IP_ADDRESS
    objref:
      kind: ConfigMap
      name: params-config
      apiVersion: v1
    fieldref:
      fieldpath: data.VIP_IP_ADDRESS
