apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/deployment.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/jmx-exporter-config.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/metrics-patch.yaml
  - ./ns-velocity.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
    patch: |-
      - op: add
        path: /metadata/namespace
        value: velocity-sv
