apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # template
  - ../templates/minecraft-proxy
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml

patches:
  - target:
      kind: Service
      name: mc-proxy-lb
    patch: |-
      - op: replace
        path: /spec/loadBalancerIP
        value: 192.168.15.70
