apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # template
  - ../../templates/minecraft-proxy
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml
configMapGenerator:
patches:
  # deployment.yamlのmanifest編集
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
    patch: |-
      - op: replace
        path: /metadata/name
        value: velocity
      - op: replace
        path: /metadata/labels/app
        value: velocity
      - op: replace
        path: /spec/selector/matchLabels/app
        value: velocity
      - op: replace
        path: /spec/template/metadata/labels/app
        value: velocity
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1024Mi
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: velocity
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: 1024m
