apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/app-templates/minecraft-proxy/kustomization.yaml
  - ./ns-velocity.yaml
  - ./velocity-lb.yaml
  - ./plugin-configs.yaml
  - ./velocity-config.yaml
