apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # template
  - ../templates/minecraft-proxy
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml
  # 環境変数
  - ./env.yaml
configurations:
  - varReference.yaml
vars:
  - name: RESOURCE_MEMORY
    objref:
      kind: ConfigMap
      name: mc-proxy-env
      apiVersion: v1
    fieldref:
      fieldpath: data.RESOURCE_MEMORY
  - name: RESOURCE__PROXY_MEMORY
    objref:
      kind: ConfigMap
      name: mc-proxy-env
      apiVersion: v1
    fieldref:
      fieldpath: data.RESOURCE__PROXY_MEMORY
  - name: LOAD_BALANCER_IP
    objref:
      kind: ConfigMap
      name: mc-proxy-env
      apiVersion: v1
    fieldref:
      fieldpath: data.LOAD_BALANCER_IP
