apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  # namespace
  - ./ns-velocity.yaml
  # template
  - ../templates/minecraft-proxy
  # velocity-config
  - ./velocity-config.yaml
  # plugin-config
  - ./plugin-config.yaml

configMapGenerator:
  - name: env-config
    envs:
      - ./variables.env

vars:
  - name: LOAD_BALANCER_IP
    objref:
      kind: ConfigMap
      name: env-config
      apiVersion: v1
    fieldref:
      fieldPath: data.LOAD_BALANCER_IP
