apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  - ../../app/templates/minecraft-proxy/kustomization.yaml
  - ./ns-velocity.yaml
  - ./velocity-lb.yaml
  - ./plugin-configs.yaml
  - ./velocity-config.yaml
