apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velocity-sv
resources:
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/deployment.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/jmx-exporter-config.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-proxy/metrics-patch.yaml
  - ./ns-velocity.yaml
patches:
  # deployment.yamlのmanifest編集
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: velocity-sv
      - op: replace
        path: /metadata/name
        value: velocity
      - op: replace
        path: /metadata/labels/app
        value: velocity
      - op: replace
        path: /spec/selector/matchLabels/app
        value: velocity
      - op: replace
        path: /spec/template/metadata/labels/app
        value: velocity
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: velocity
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1024Mi
      - op: replace
        path: /spec/template/spec/containers/1/env/0/value
        value: 1024m
