apiVersion: v1
kind: Namespace
metadata:
  name: velocity-sv
  labels:
    name: velocity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velocity-sv
  name: velocity
  labels:
    app: velocity
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      initContainers:
        - name: server-icon-downloader
          image: busybox:1.36.1
          env:
            - name: SERVER_ICON_URL
              value: "https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/a47b0c0ad303f248f1d50a7b5b3ac508f4435389/minecraft/branding/server-icon.png"
          volumeMounts:
            - name: server-icon-download-volume
              mountPath: /root/server-icon-download
          command:
            - "sh"
            - "-c"
            - 'wget -O /root/server-icon-download/server-icon.png "${SERVER_ICON_URL}"'
        - name: jmx-exporter-downloader
          image: busybox:1.36.0
          env:
            - name: JMX_EXPORTER_URL
              value: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar"
          volumeMounts:
            - name: jmx-exporter-download-volume
              mountPath: /root/jmx-exporter-download
          command:
            - "sh"
            - "-c"
            - 'wget -O /root/jmx-exporter-download/jmx-exporter-javaagent.jar "${JMX_EXPORTER_URL}"'
        - name: geyser-downloader
          image: busybox:1.36.1
          env:
            - name: GEYSER_URL
              value: "https://download.geysermc.org/v2/projects/geyser/versions/2.3.1/builds/539/downloads/velocity"
          volumeMounts:
            - name: geyser-download-volume
              mountPath: /root/geyser-download
          command:
            - "sh"
            - "-c"
            - 'curl -o /root/geyser-download/geyser-velocity.jar "${GEYSER_URL}"'
      nodeSelector:
        kubernetes.io/hostname: onp-k8s-wk-3
      containers:
        - image: itzg/bungeecord:java17-2022.4.1
          name: velocity
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: VELOCITY
            - name: ENABLE_RCON
              value: "true"
            - name: MEMORY
              value: 768m
            - name: PLUGINS
              value: >-
                https://github.com/weihao/bungeecord-prometheus-exporter/releases/download/3.2.5/bungeecord-prometheus-exporter-3.2.5.jar,
                https://download.luckperms.net/1543/velocity/LuckPerms-Velocity-5.4.130.jar,
                https://github.com/Camotoy/GeyserSkinManager/releases/download/1.7/GeyserSkinManager-Velocity.jar
            - name: JVM_OPTS
              value: >-
                -javaagent:/jmx-exporter/jmx-exporter-javaagent.jar=18321:/jmx-exporter/jmx-exporter-config.yaml
          ports:
            - containerPort: 25577
              name: velocity
            - containerPort: 18321
              name: jmx-metrics
            - containerPort: 9225
              name: metrics
          volumeMounts:
            - name: server-icon-download-volume
              mountPath: /config/server-icon.png
              subPath: server-icon.png
            - name: jmx-exporter-download-volume
              mountPath: /jmx-exporter/jmx-exporter-javaagent.jar
              subPath: jmx-exporter-javaagent.jar
            - name: jmx-exporter-config
              mountPath: /jmx-exporter/jmx-exporter-config.yaml
              subPath: jmx-exporter-config.yaml
            - name: geyser-download-volume
              mountPath: /server/plugins/geyser-velocity.jar
              subPath: geyser-velocity.jar
      volumes:
        - name: jmx-exporter-download-volume
          emptyDir: {}
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config
        - name: server-icon-download-volume
          emptyDir: {}
        - name: geyser-download-volume
          emptyDir: {}
