apiVersion: v1
kind: Namespace
metadata:
  name: velocity-sv
  labels:
    name: velocity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velocity-sv
  name: velocity
  labels:
    app: velocity
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      nodeSelector:
        kubernetes.io/hostname: onp-k8s-wk-3
      containers:
        - image: itzg/bungeecord:java17-2022.4.1
          name: velocity
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: VELOCITY
            - name: ENABLE_RCON
              value: "true"
            - name: MEMORY
              value: 768m
          ports:
            - containerPort: 25577
              name: velocity
            - containerPort: 18321
              name: jmx-metrics
            - containerPort: 9225
              name: metrics
