apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - image: itzg/minecraft-server:java17
          name: minecraft
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: PAPER
            - name: ENABLE_RCON
              value: "true"
            - name: VERSION
              value: "1.20.1"
            - name: DIFFICULTY
              value: peaceful
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
            - name: PLUGINS
              value: >-
                https://github.com/ViaVersion/ViaVersion/releases/download/4.7.0/ViaVersion-4.7.0.jar,
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v2.5.0/minecraft-prometheus-exporter-2.5.0.jar
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            - name: server-config
              mountPath: /data/bukkit.yml
              subPath: bukkit.yml
            - name: server-config
              mountPath: /data/server.properties
              subPath: server.properties
            - name: server-config
              mountPath: /data/spigot.yml
              subPath: spigot.yml
#            - name: server-plugin-config
#              mountPath: /data/plugins/PrometheusExporter/config.yml
#              subPath: prometheusexporter.yml

      volumes:
        - name: minecraft-storage
          persistentVolumeClaim:
            claimName: minecraft-pvc
        - name: server-config
          configMap:
            name: common-mcserver-configs
#        - name: server-plugin-config
#          configMap:
#            name: common-mcserver-plugin-configs
