apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    name: minecraft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - image: itzg/minecraft-server:java17
          name: minecraft
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: PAPER
            - name: ENABLE_RCON
              value: "true"
            - name: VERSION
              value: "1.20.1"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
            - name: DIFFICULTY
              value: easy
            - name: ONLINE_MODE
              value: "FALSE"
            - name: PLUGINS
              # ViaVersion:
              #   https://github.com/ViaVersion/ViaVersion/releases/download/4.7.0/ViaVersion-4.7.0.jar
              # minecraft-prometheus-exporter:
              #   https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v2.5.0/minecraft-prometheus-exporter-2.5.0.jar
              value: >-
                https://github.com/ViaVersion/ViaVersion/releases/download/4.7.0/ViaVersion-4.7.0.jar,
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v2.5.0/minecraft-prometheus-exporter-2.5.0.jar
              # mysql-inventory-bridge:
              #   https://www.spigotmc.org/resources/mysql-inventory-bridge.7849/
              # iportal:
              #   https://www.spigotmc.org/resources/iportal-transportation-bungeecord-portals.29552/
            - name: SPIGET_RESOURCES
              value: 7849,29552
          ports:
            - name: minecraft
              containerPort: 25565
            - name: mc-metrics
              containerPort: 9225
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            - name: minecraft-storage
              mountPath: /data
            - name: mcserver-config
              mountPath: /data/bukkit.yml
              subPath: mc-bukkit.yml
            - name: mcserver-config
              mountPath: /data/spigot.yml
              subPath: mc-spigot.yml
            - name: mcserver-plugin-config
              mountPath: /plugins/PrometheusExporter/config.yml
              subPath: prometheusexporter.yml
            - name: mcserver-plugin-config
              mountPath: /plugins/MysqlInventoryBridge/config.yml
              subPath: mysqlinventorybridge.yml

      volumes:
        - name: minecraft-storage
          persistentVolumeClaim:
            claimName: minecraft-pvc
        - name: mcserver-config
          configMap:
            name: mcserver-configs
        - name: mcserver-plugin-config
          configMap:
            name: mcserver-plugin-configs
