apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mc-sv
  name: mc-pvc
  labels:
    app: mc
spec:
  storageClassName: mc-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
