apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mc-sv
  name: mc-pv
  labels:
    app: mc
spec:
  storageClassName: mc-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/minecraft/
  persistentVolumeReclaimPolicy: Retain
