apiVersion: v1
kind: Service
metadata:
  namespace: mc-sv
  name: mc-service
  labels:
    app: mc
spec:
  type: ClusterIP
  ports:
  - name: mc
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc
