apiVersion: v1
kind: ConfigMap
metadata:
  namespace: minecraft
  name: common-mcserver-plugin-configs
data:
  prometheusexporter-config.yml: |
    host: 192.168.15.71
    port: 9225
    enable_metrics:
      entities_total: true
      villagers_total: true
      loaded_chunks_total: true
      jvm_memory: true
      players_online_total: true
      players_total: true
      tps: true
      world_size: true
      jvm_threads: true
      jvm_gc: true
      tick_duration_median: true
      tick_duration_average: true
      tick_duration_min: false
      tick_duration_max: true
      player_online: false
      player_statistic: false
