apiVersion: v1
kind: Service
metadata:
  namespace: mc-sv
  name: mc-service
  labels:
    app: mc
spec:
  type: ClusterIP
  ports:
  - name: mc
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-sv
  name: mc-rcon-service
  labels:
    app: mc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.15.71
  ports:
    - name: rcon-service
      port: 25575
      protocol: TCP
      targetPort: 25575
  selector:
    app: mc
