apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-sv
  name: mc
  labels:
    app: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      initContainers:
      containers:
        - image: itzg/minecraft-server:java21
          name: mc
          env:
            # minecraftのeulaについて「同意」の宣言
            - name: EULA
              value: "TRUE"
            # サーバーのtime設定を日本標準時に
            - name: TZ
              value: Asia/Tokyo
            # 本docer_imageの起動サーバ宣言を指定
            - name: TYPE
              value: PAPER
            # 本docer_imageの起動サーバーverを指定
            - name: VERSION
              value: "1.20.6"
            # rconの設定を「true」に
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              value: "maroncloud"
            # 最小利用メモリ
            - name: INIT_MEMORY
              value: 1G
            # 最大利用メモリ
            - name: MAX_MEMORY
              value: 2G
            # ゲーム難易度
            - name: DIFFICULTY
              value: easy
            # velocity経由でのログインのためfalseに設定
            - name: ONLINE_MODE
              value: "FALSE"
            - name: PLUGINS
              # minecraft-prometheus-exporter
              # LuckPerms-Bukkit
              # Advanced-Portals-0.9.3
              # LunaChat
              value: >-
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar,
                https://download.luckperms.net/1552/bukkit/loader/LuckPerms-Bukkit-5.4.137.jar,
                https://github.com/sekwah41/Advanced-Portals/releases/download/v0.9.3/Advanced-Portals-0.9.3.jar,
                https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar
            # Spiget API経由でダウンロード可能なpluginは本docer_imageの機能を活用し格納
            - name: SPIGET_RESOURCES
              # mysql-inventory-bridge:  (https://www.spigotmc.org/resources/mysql-inventory-bridge.7849/)
              # DecentHolograms:  (https://www.spigotmc.org/resources/decentholograms-1-8-1-20-1-papi-support-no-dependencies.96927/)
              value: 7849,96927
          ports:
            - name: mc
              containerPort: 25565
            - name: mc-rcon
              containerPort: 25575
            - name: mc-metrics
              containerPort: 9225
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            # mc-musicサーバーの永続ストレージマウント
            - name: minecraft-storage
              mountPath: /data
            # bukkit configのマウント
            - name: mcserver-config
              mountPath: /config/bukkit.yml
              subPath: mc-bukkit.yml
            # spigot configのマウント
            - name: mcserver-config
              mountPath: /config/spigot.yml
              subPath: mc-spigot.yml
            # paper-global configのマウント
            - name: mcserver-config
              mountPath: /config/paper-global.yml
              subPath: mc-paper-global.yml
            # PrometheusExporter configのマウント
            - name: mcserver-plugin-config
              mountPath: /plugins/PrometheusExporter/config.yml
              subPath: prometheusexporter.yml
            # MysqlInventoryBridge configのマウント
            - name: mcserver-plugin-config
              mountPath: /plugins/MysqlInventoryBridge/config.yml
              subPath: mysqlinventorybridge.yml
            # LuckPerms configのマウント
            - name: mcserver-plugin-config
              mountPath: /plugins/LuckPerms/config.yml
              subPath: LuckPerms-config.yml
            # LunaChat configのマウント
            - name: mcserver-plugin-config
              mountPath: /plugins/LunaChat/config.yml
              subPath: LunaChat-config.yml   
            # AdvancedPortals configのマウント
            - name: mcserver-plugin-config
              mountPath: /plugins/AdvancedPortals/config.yml
              subPath: Advanced-config.yml
            # AdvancedPortals_destinations configのマウント
            - name: mcserver-plugin-config
              mountPath: /plugins/AdvancedPortals/destinations.yml
              subPath: Advanced-destinations.yml
            # AdvancedPortals_portals configのマウント
            - name: mcserver-plugin-config
              mountPath: /plugins/AdvancedPortals/portals.yml
              subPath: Advanced-portals.yml
      volumes:
        # minecraft-musicサーバーの永続ストレージの指定
        - name: minecraft-storage
          persistentVolumeClaim:
            claimName: minecraft-pvc
        # configmapであるmcserver-configsの指定
        - name: mcserver-config
          configMap:
            name: mcserver-configs
        # configmapであるmcserver-music-plugin-configsの指定
        - name: mcserver-plugin-config
          configMap:
            name: mcserver-plugin-configs
