apiVersion: v1
kind: ConfigMap
metadata:
  namespace: waterfall
  name: bungeecord-config
data:
  config.yml: |
    servers:
      lobby:
        motd: '&1Just another Waterfall - Forced Host'
        address: 192.168.15.87:25565
        restricted: false
      s1:
        motd: '&1Just another Waterfall - Forced Host'
        address: 192.168.15.88:25565
        restricted: false
      s2:
        motd: '&1Just another Waterfall - Forced Host'
        address: 192.168.15.89:25565
        restricted: false
      k8s:
        motd: '&1Just another Waterfall - Forced Host'
        address: 192.168.15.71:25565
        restricted: false
    listeners:
      - priorities:
          - lobby
        forced_hosts:
          pvp.md-5.net: pvp
        query_port: 25565
        motd: '&1Another Bungee server'
        bind_local_address: true
        tab_list: GLOBAL_PING
        query_enabled: false
        host: 0.0.0.0:53616
        max_players: 256
        tab_size: 60
        ping_passthrough: false
        force_default_server: true
        proxy_protocol: false
    # Warning: asterisk cannot be used for permissions setting
    permissions:
      default:
        - bungeecord.command.server
      admin:
        - bungeecord.command.list
        - bungeecord.command.alert
        - bungeecord.command.end
        - bungeecord.command.ip
        - bungeecord.command.reload
        - bungeecord.command.kick
    groups:
      maron_12345:
        - admin
    custom_server_name: HexaCord
    player_limit: -1
    online_mode: true
    forge_support: false
    stats: 752477ce-c5e9-4e37-9361-2d4f26f65f14
    ip_forward: true
    prevent_proxy_connections: true
    always_handle_packets: false
    remote_ping_timeout: 5000
    remote_ping_cache: -1
    # The timeout value must be set shorter than the upper network
    timeout: 20000
    server_connect_timeout: 5000
    connection_throttle: 2000
    connection_throttle_limit: 16
    network_compression_threshold: 256
    log_pings: false
    disabled_commands:
    log_commands: true
    inject_commands: false
