kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bungeecord-pvc
  namespace: waterfall
  labels:
    app: bungeecord
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
