apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: waterfall
  name: bungeecord
  labels:
    app: bungeecord
  # We wish this deployment to be reloaded
  # when "bungeecord-config" and "bungeecord-plugin-configs" ConfigMap are updated
  annotations:
    configmap.reloader.stakater.com/reload: "jmx-exporter-config,bungeecord-config,bungeecord-plugin-configs"
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bungeecord
  template:
    metadata:
      labels:
        app: bungeecord
    spec:
      initContainers:
        - name: jmx-exporter-downloader
          image: busybox:1.36.0
          env:
            - name: JMX_EXPORTER_URL
              value: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar"
          volumeMounts:
            - name: jmx-exporter-download-volume
              mountPath: /root/jmx-exporter-download
          command:
            - "sh"
            - "-c"
            - 'wget -O /root/jmx-exporter-download/jmx-exporter-javaagent.jar "${JMX_EXPORTER_URL}"'
      nodeSelector:
        kubernetes.io/hostname: onp-k8s-wk-3
      containers:
        - image: itzg/bungeecord:java17-2022.4.1
          name: bungeecord
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: WATERFALL
            - name: ENABLE_RCON
              value: "true"

            - name: INIT_MEMORY
              value: 512M
            - name: MAX_MEMORY
              value: 1G
            - name: PLUGINS
              value: >-
                https://github.com/weihao/bungeecord-prometheus-exporter/releases/download/3.1.5/bungeecord-prometheus-exporter-3.1.5.jar,
                https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar
            # BungeeYAML (depended by SwiftMOTD):
            #   https://www.spigotmc.org/resources/bungeeyaml-original.13068/
            # SwiftMOTD:
            #   https://www.spigotmc.org/resources/swiftmotd.221/
            - name: SPIGET_PLUGINS
              value: 13068,221

            - name: JVM_OPTS
              value: >-
                -javaagent:/jmx-exporter/jmx-exporter-javaagent.jar=18321:/jmx-exporter/jmx-exporter-config.yaml
          ports:
            - containerPort: 25577
              name: bungeecord
            - containerPort: 18321
              name: jmx-metrics
            - containerPort: 9225
              name: metrics
          volumeMounts:
            - name: bungeecord-config
              mountPath: /config/config.yml
              subPath: config.yml
            - name: bungeecord-plugin-configs
              mountPath: /config/plugins/BungeeCordPrometheusExporter/config.json
              subPath: BungeeCordPrometheusExporter-config.json
            - name: bungeecord-plugin-configs
              mountPath: /config/plugins/SwiftMOTD/config.yml
              subPath: SwiftMOTD-config.yml

            # JMX exporter 周りのファイルが入ったボリューム達のマウント設定
            - name: jmx-exporter-download-volume
              mountPath: /jmx-exporter/jmx-exporter-javaagent.jar
              subPath: jmx-exporter-javaagent.jar
            - name: jmx-exporter-config
              mountPath: /jmx-exporter/jmx-exporter-config.yaml
              subPath: jmx-exporter-config.yaml

      volumes:
        - name: bungeecord-storage
          persistentVolumeClaim:
            claimName: bungeecord-pvc
        - name: bungeecord-config
          configMap:
            name: bungeecord-config
        - name: bungeecord-plugin-configs
          configMap:
            name: bungeecord-plugin-configs
        # JMX exporterをinitContainerでダウンロードしてBugneeCordに受け渡すためのvolume
        - name: jmx-exporter-download-volume
          emptyDir: {}
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config
