kind: ConfigMap
metadata:
  namespace: waterfall
  name: bungeecord-plugin-configs
apiVersion: v1
data:
  BungeeCordPrometheusExporter-config.json: |
    {
      "host": "0.0.0.0",
      "port": "9225",
      "prefix": "bungeecord_",
      "jvm_gc": "true",
      "jvm_memory": "true",
      "jvm_threads": "true",
      "player_connects": "true",
      "player_disconnects": "true",
      "server_list_pings": "true",
      "managed_servers": "true",
      "online_players": "true",
      "redis_player_connects": "false",
      "redis_player_disconnects": "false",
      "redis_online_players": "false",
      "redis_bungee_online_proxies": "false"
    }

  SwiftMOTD-config.yml: |
    # Override if necessary.
    motds:
      generic: 
      - '&cJoin now!%newline&d&oYou wont regret it!'
      - '&eClick me &6&lNOW&e!%newline&aWoop, I haz your multilinez!'
      - '&c&k||| &aBest server ever! &c&k|||'
      dynamic: 
      - '&aHi, &6%player&a!%newline&eWoop, multi-line!'
      - '&e%player, &cI command you to join!%newline&cOr burn in &lhell!!'
      - '&dWe know you want it, &b%player&d!'
