apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-lobby-sv
resources:
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/statefulset.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/service.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/jmx-exporter-config.yaml
  - ./ns-mc-lobby-sv.yaml
patches:
  - target:
      kind: StatefulSet
      name: mc-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: mc-lobby
      - op: replace
        path: /metadata/labels
        value: mc-lobby
      - op: replace
        path: /spec/selector/app
        value: mc-lobby
      - op: replace
        path: /spec/template/metadata/labels/app
        value: mc-lobby
      - op: add
        path: /spec/template/spec/initContainers
        value:
          name: download-world
          image: busybox:1.36.1
          env:
            - name: WORLD_URL
              value: "https://github.com/maron-gt123/k8s-setup-for-proxmox/releases/download/1.0/world.tar"
          volumeMounts:
            - name: world-download-volume
              mountPath: /root/world-download
          command:
            - sh
            - -c
            - >
              echo "start downloading world data" &&
              wget --no-check-certificate -qO /root/world-download/world.tar "${WORLD_URL}" &&
              tar -xvf /root/world-download/world.tar -C /root/world-download/ &&
              rm /root/world-download/world.tar &&
              echo "successfully imported world data"
