apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-lobby-sv
resources:
  # namespace
  - ./ns-mc-lobby-sv.yaml
  # template
  - ../templates/minecraft-server
  # mc-config
  - ./mc-lobby-configs.yaml
  # advancedportals
  - ./mc-plugin-advancedportals-configs.yaml
  # holograms
  - ./mc-plugin-holograms-configs.yaml

patches:
  - target:
      kind: StatefulSet
      name: minecraft
    patch: |-
      # world dataのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: world-download-volume
          mountPath: /data/world
      # world dataの格納先
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: world-download-volume
          emptyDir: {}
          
      # ------minecraft lobby用plugins関連------
      # world-editのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: init-download-volume
          mountPath: /data/plugins/worldedit.jar
          subPath: worldedit.jar
      # world-guardのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: init-download-volume
          mountPath: /data/plugins/worldguard.jar
          subPath: worldguard.jar
      # spawnのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: init-download-volume
          mountPath: /data/plugins/Spawn-2.4.1.jar
          subPath: Spawn-2.4.1.jar
      # hologramsのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-holograms-config
          mountPath: /config/plugins/DecentHolograms/holograms/holograms-S1_Gateway.yml
          subPath: holograms-S1_Gateway.yml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-holograms-config
          mountPath: /config/plugins/DecentHolograms/holograms/holograms-S2_Gateway.yml
          subPath: holograms-S2_Gateway.yml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-holograms-config
          mountPath: /config/plugins/DecentHolograms/holograms/holograms-music-Gateway.yml
          subPath: holograms-music-Gateway.yml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-holograms-config
          mountPath: /config/plugins/DecentHolograms/holograms/holograms-k8s_Gateway.yml
          subPath: holograms-k8s_Gateway.yml
      - op: add
        path: /spec/template/spec/volumes/-
        value: 
          name: mc-plugin-holograms-config
          configMap:
            name: mc-plugin-holograms-configs
