apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-lobby-sv
resources:
  # namespace
  - ./ns-mc-lobby-sv.yaml
  # statefulset
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/statefulset.yaml
  # service
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/service.yaml
  # metrics-service
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/refs/heads/main/k8s/manifests/apps/templates/minecraft-server/mc-metrics-patch.yaml
  # mc-config
  - ./mc-lobby-configs.yaml
  # mc-common-plugin-config
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/refs/heads/main/k8s/manifests/apps/templates/minecraft-server/mc-common-plugin-config.yaml
  #  imx-exporter-config
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/jmx-exporter-config.yaml
  # luckperms
  - ./mc-plugin-luckperms-configs.yaml
  # luckperms
  - ./mc-lobby-plugin-holograms-configs.yaml
patches:
  - target:
      kind: StatefulSet
      name: mc-template
    patch: |-
      # server.propertiesの編集
      # ALLOW_NETHER
      - op: replace
        path: /spec/template/spec/containers/0/env/7/value
        value: "false"
      # DIFFICULTY
      - op: replace
        path: /spec/template/spec/containers/0/env/8/value
        value: peaceful
      # LEVEL_TYPE
      - op: replace
        path: /spec/template/spec/containers/0/env/10/value
        value: flat
      # SPAWN_ANIMALS
      - op: replace
        path: /spec/template/spec/containers/0/env/11/value
        value: "false"
      # SPAWN_MONSTERS
      - op: replace
        path: /spec/template/spec/containers/0/env/12/value
        value: "false"
      # SPAWN_NPCS
      - op: replace
        path: /spec/template/spec/containers/0/env/13/value
        value: "false"
      # ENABLE_WHITELIST
      - op: replace
        path: /spec/template/spec/containers/0/env/14/value
        value: "true"
      # whitelistマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: mc-config
          mountPath: /config/whitelist.json
          subPath: mc-whitelist.json
      # world dataのダウンロード
      - op: add
        path: /spec/template/spec/initContainers/-
        value:
          name: download-world
          image: busybox:1.36.1
          env:
            - name: WORLD_URL
              value: "https://github.com/maron-gt123/k8s-setup-for-proxmox/releases/download/1.0/world.tar"
          volumeMounts:
            - name: world-download-volume
              mountPath: /root/world-download
          command:
            - sh
            - -c
            - >
              echo "start downloading world data" &&
              wget --no-check-certificate -qO /root/world-download/world.tar "${WORLD_URL}" &&
              tar -xvf /root/world-download/world.tar -C /root/world-download/ &&
              rm /root/world-download/world.tar &&
              echo "successfully imported world data"
      # world edit & guardのダウンロード
      - op: add
        path: /spec/template/spec/initContainers/-
        value:
          name: plugins-download
          image: busybox:1.36.1
          env:
            - name: WORLDEDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/5935693/download"
            - name: WORLDGUARD_URL
              value: "https://dev.bukkit.org/projects/worldguard/files/5888870/download"
            - name: SPAWN_URL
              value: "https://cdn.modrinth.com/data/Pw3KRjwE/versions/mgrZ4A8t/Spawn-2.4.1.jar"
          volumeMounts:
            - name: world-edit-download-volume
              mountPath: /root/world-edit-download
            - name: world-guard-download-volume
              mountPath: /root/world-guard-download
            - name: spawn-download-volume
              mountPath: /root/spawn-download
          command:
            - sh
            - -c
            - >
              wget -O /root/world-edit-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/world-guard-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/spawn-download/Spawn-2.4.1.jar "${SPAWN_URL}"
      # world dataのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: world-download-volume
          mountPath: /data/world
      # world-editのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: world-edit-download-volume
          mountPath: /data/plugins/worldedit.jar
          subPath: worldedit.jar
      # world-guardのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: world-guard-download-volume
          mountPath: /data/plugins/worldguard.jar
          subPath: worldguard.jar
      # spawnのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: spawn-download-volume
          mountPath: /data/plugins/Spawn-2.4.1.jar
          subPath: Spawn-2.4.1.jar
      # hologramsのマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-config
          mountPath: /data/plugins/DecentHolograms/holograms/holograms-S1_Gateway.yml
          subPath: holograms-S1_Gateway.yml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-config
          mountPath: /data/plugins/DecentHolograms/holograms/holograms-S2_Gateway.yml
          subPath: holograms-S2_Gateway.yml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-config
          mountPath: /data/plugins/DecentHolograms/holograms/holograms-music-Gateway.yml
          subPath: holograms-music-Gateway.yml
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: mc-plugin-config
          mountPath: /data/plugins/DecentHolograms/holograms/holograms-k8s_Gateway.yml
          subPath: holograms-k8s_Gateway.yml
      # world dataの格納先
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: world-download-volume
          emptyDir: {}
      # world-editの格納先
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: world-edit-download-volume
          emptyDir: {}
      # world-guardの格納先
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: world-guard-download-volume
          emptyDir: {}
      # spawnの格納先
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: spawn-download-volume
          emptyDir: {}
