apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-lobby-sv
resources:
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/statefulset.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/service.yaml
  - https://raw.githubusercontent.com/maron-gt123/k8s-setup-for-proxmox/main/k8s/manifests/apps/templates/minecraft-server/jmx-exporter-config.yaml
  - ./ns-mc-lobby-sv.yaml
  - ./mc-lobby-configs.yaml

patches:
  - target:
      kind: StatefulSet
      name: mc-template
    patch: |-
      # name関連の編集
      - op: replace
        path: /metadata/name
        value: mc-lobby
      - op: replace
        path: /metadata/labels/app
        value: mc-lobby
      - op: replace
        path: /spec/selector/matchLabels/app
        value: mc-lobby
      - op: replace
        path: /spec/template/metadata/labels/app
        value: mc-lobby
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: mc-lobby
      # server.propertiesの編集
      # ALLOW_NETHER
      - op: replace
        path: /spec/template/spec/containers/0/env/7/value
        value: "false"
      # DIFFICULTY
      - op: replace
        path: /spec/template/spec/containers/0/env/8/value
        value: peaceful
      # LEVEL_TYPE
      - op: replace
        path: /spec/template/spec/containers/0/env/10/value
        value: flat
      # SPAWN_ANIMALS
      - op: replace
        path: /spec/template/spec/containers/0/env/11/value
        value: "false"
      # SPAWN_MONSTERS
      - op: replace
        path: /spec/template/spec/containers/0/env/12/value
        value: "false"
      # SPAWN_NPCS
      - op: replace
        path: /spec/template/spec/containers/0/env/13/value
        value: "false"
      # ENABLE_WHITELIST
      - op: replace
        path: /spec/template/spec/containers/0/env/14/value
        value: "true"
      # ホワイトリストマウント
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: mc-config
          mountPath: /config/whitelist.json
          subPath: mc-whitelist.json
      # world dataのダウンロード
      - op: add
        path: /spec/template/spec/initContainers/-
        value:
          name: download-world
          image: busybox:1.36.1
          env:
            - name: WORLD_URL
              value: "https://github.com/maron-gt123/k8s-setup-for-proxmox/releases/download/1.0/world.tar"
          volumeMounts:
            - name: world-download-volume
              mountPath: /root/world-download
          command:
            - sh
            - -c
            - >
              echo "start downloading world data" &&
              wget --no-check-certificate -qO /root/world-download/world.tar "${WORLD_URL}" &&
              tar -xvf /root/world-download/world.tar -C /root/world-download/ &&
              rm /root/world-download/world.tar &&
              echo "successfully imported world data"
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          name: world-download-volume
          mountPath: /data/world
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: world-download-volume
          emptyDir: {}
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: world-edit-download-volume
          emptyDir: {}
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: world-guard-download-volume
          emptyDir: {}
  - target:
      kind: Service
      name: mc-template-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: mc-lobby-service
      - op: replace
        path: /metadata/labels/app
        value: mc-lobby
      - op: replace
        path: /spec/selector/app
        value: mc-lobby
