apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: WORLDEDIT_URL
              value: "https://cdn.modrinth.com/data/1u6JkXh5/versions/HIoAq6RI/worldedit-bukkit-7.3.10-beta-01.jar"
            - name: WORLDGUARD_URL
              value: "https://cdn.modrinth.com/data/DKY9btbd/versions/S1KKDczu/worldguard-bukkit-7.0.13-beta-2-dist.jar"
            - name: SPAWN_URL
              value: "https://cdn.modrinth.com/data/Pw3KRjwE/versions/mgrZ4A8t/Spawn-2.4.1.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/initContainer-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/initContainer-download/Spawn-2.4.1.jar "${SPAWN_URL}"
        # ------minecraft lobbyのワールド生成関連------
        - name: download-world
          image: busybox:1.36.1
          env:
            - name: WORLD_URL
              value: "https://github.com/maron-gt123/k8s-setup-for-proxmox/releases/download/1.0/world.tar"
          volumeMounts:
            - name: world-download-volume
              mountPath: /root/world-download
          command:
            - sh
            - -c
            - >
              echo "start downloading world data" &&
              wget --no-check-certificate -qO /root/world-download/world.tar "${WORLD_URL}" &&
              tar -xvf /root/world-download/world.tar -C /root/world-download/ &&
              rm /root/world-download/world.tar &&
              echo "successfully imported world data"
      containers:
        - env:
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: "lobby"
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
