apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: WORLDEDIT_URL
              value: "https://cdn.modrinth.com/data/1u6JkXh5/versions/HIoAq6RI/worldedit-bukkit-7.3.10-beta-01.jar"
            - name: WORLDGUARD_URL
              value: "https://cdn.modrinth.com/data/DKY9btbd/versions/S1KKDczu/worldguard-bukkit-7.0.13-beta-2-dist.jar"
            - name: SPAWN_URL
              value: "https://cdn.modrinth.com/data/Pw3KRjwE/versions/mgrZ4A8t/Spawn-2.4.1.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/initContainer-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/initContainer-download/Spawn-2.4.1.jar "${SPAWN_URL}"
