apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: mc-lobby-sv
  labels:
    app: mc-lobby
    release: prometheus
  name: mc-lobby-metrics
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: mc-lobby
      role: metrics
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-lobby-sv
  name: mc-metrics
  labels:
    app: mc-lobby
    role: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9225
      protocol: TCP
      targetPort: metrics
  selector:
    app: mc-lobby
