apiVersion: v1
kind: Service
metadata:
  namespace: mc-lobby-sv
  name: mc-lobby-service
  labels:
    app: mc-lobby
spec:
  type: ClusterIP
  ports:
  - name: mc-lobby
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc-lobby
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-lobby-sv
  name: mc-lobby-rcon-service
  labels:
    app: mc-lobby
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.15.71
  ports:
    - name: rcon-service
      port: 25575
      protocol: TCP
      targetPort: 25575
  selector:
    app: mc-lobby
