apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-lobby-sv
  name: mc-lobby
  labels:
    app: mc-lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-lobby
  template:
    metadata:
      labels:
        app: mc-lobby
    spec:
      initContainers:
        # lobbyサーバーをgithubに格納されているワールドデータに指定するためのダウンロード及び配置作業
        - name: download-world
          image: busybox:1.36.1
          env:
            - name: WORLD_URL
              value: "https://github.com/maron-gt123/k8s-setup-for-proxmox/releases/download/1.0/world.tar"
          volumeMounts:
            - name: world-download-volume
              mountPath: /root/world-download
          command:
            - sh
            - -c
            - >
              echo "start downloading world data" &&
              wget --no-check-certificate -qO /root/world-download/world.tar "${WORLD_URL}" &&
              tar -xvf /root/world-download/world.tar -C /root/world-download/ &&
              rm /root/world-download/world.tar &&
              echo "successfully imported world data"
        # pluginデータのダウンロード及び配置
        - name: plugins-downloader
          image: busybox:1.36.1
          env:
            - name: WORLD_EDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/5507246/download"
            - name: WORLD_GUARD_URL
              value: "https://dev.bukkit.org/projects/worldguard/files/5344377/download"
          volumeMounts:
            - name: world-edit-download-volume
              mountPath: /root/world-edit-download
            - name: world-guard-download-volume
              mountPath: /root/world-guard-download
          command:
            - sh
            - -c
            - >
              wget -O /root/world-edit-download/worldedit-bukkit.jar "${WORLD_EDIT_URL}" &&
              wget -O /root/world-guard-download/worldguard-bukkit.jar "${WORLD_GUARD_URL}"
      containers:
        - image: itzg/minecraft-server:java21
          name: mc-lobby
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: PAPER
            - name: VERSION
              value: "1.20.6"
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              value: "maron_cloud"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: ONLINE_MODE
              value: "FALSE"
            - name: LEVEL_TYPE
              value: flat
            - name: SPAWN_ANIMALS
              value: "false"
            - name: SPAWN_MONSTERS
              value: "false"
            - name: SPAWN_NPCS
              value: "false"
            - name: ENABLE_WHITELIST
              value: "true"
            - name: PLUGINS
              # フルpathのpluginが公開されているものはここで直接ダウンロードし/data/pluginsに格納
              # minecraft-prometheus-exporter3.1.0
              # LuckPerms-Bukkit5.4.137
              # Advanced-Portals-0.9.3
              # LunaChat
              # DecentHolograms
              # SpawnPlugin
              value: >-
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar,
                https://download.luckperms.net/1552/bukkit/loader/LuckPerms-Bukkit-5.4.137.jar,
                https://github.com/sekwah41/Advanced-Portals/releases/download/v0.10.0/Advanced-Portals-0.10.0.jar,
                https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar,
                https://github.com/DecentSoftware-eu/DecentHolograms/releases/download/2.8.9/DecentHolograms-2.8.9.jar,
                https://mc-plugins.net/_cdn/plugins/bukkit-spigot/SpawnPlugin_1.0.3.jar
            # config関連を/configから/dataへmcopy
            - name: COPY_CONFIG_DEST
              value: /data
          ports:
            - name: mc-lobby
              containerPort: 25565
            - name: rcon-lobby
              containerPort: 25575
            - name: mc-metrics
              containerPort: 35353
            - name: jmx-metrics
              containerPort: 18321
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            # world関連の格納先マウント
            - name: data
              mountPath: /data
            - name: world-download-volume
              mountPath: /data/world

            # bukkit/spigot/paper-global関連のconfigをマウント
            - name: mcserver-lobby-config
              mountPath: /config/bukkit.yml
              subPath: mc-bukkit.yml
            - name: mcserver-lobby-config
              mountPath: /config/spigot.yml
              subPath: mc-spigot.yml
            - name: mcserver-lobby-config
              mountPath: /config/config/paper-global.yml
              subPath: mc-paper-global.yml
            - name: mcserver-lobby-config
              mountPath: /config/whitelist.json
              subPath: mc-whitelist.json
            
            # world-edit/world-guardをマウント
            - name: world-edit-download-volume
              mountPath: /data/plugins/worldedit-bukkit.jar
              subPath: worldedit-bukkit.jar
            - name: world-guard-download-volume
              mountPath: /data/plugins/worldguard-bukkit.jar
              subPath: worldguard-bukkit.jar
            
            # Plugin関連のconfigをマウント
            - name: mcserver-lobby-plugin-config
              mountPath: /plugins/LuckPerms/config.yml
              subPath: luckperms.yml
            - name: mcserver-lobby-plugin-config
              mountPath: /plugins/PrometheusExporter/config.yml
              subPath: prometheusexporter.yml
            - name: mcserver-lobby-plugin-config
              mountPath: /plugins/LunaChat/config.yml
              subPath: lunachat.yml
            - name: mcserver-lobby-plugin-config
              mountPath: /plugins/WorldEdit/config.yml
              subPath: worldedit-config.yml
            - name: mcserver-lobby-plugin-config
              mountPath: /plugins/WorldGuard/config.yml
              subPath: worldgard-config.yml
            - name: mcserver-lobby-plugin-config
              mountPath: /plugins/AdvancedPortals/config.yml
              subPath: advancedportals-config.yml
            - name: mcserver-lobby-plugin-config
              mountPath: /plugins/SpawnPlugin/config.yml
              subPath: spawn.yml

            # hologramsの詳細configをマウント
            - name: mcserver-lobby-holograms-config
              mountPath: /plugins/DecentHolograms/holograms/S1_Gateway.yml
              subPath: holograms-S1_Gateway.yml
            - name: mcserver-lobby-holograms-config
              mountPath: /plugins/DecentHolograms/holograms/S2_Gateway.yml
              subPath: holograms-S2_Gateway.yml
            - name: mcserver-lobby-holograms-config
              mountPath: /plugins/DecentHolograms/holograms/music-Gateway.yml
              subPath: holograms-music-Gateway.yml
            - name: mcserver-lobby-holograms-config
              mountPath: /plugins/DecentHolograms/holograms/k8s_Gateway.yml
              subPath: holograms-k8s_Gateway.yml

            # advancedportalsの詳細configをマウント
            - name: mcserver-lobby-advancedportals-config
              mountPath: /plugins/AdvancedPortals/destinations.yml
              subPath: destinations.yml
            - name: mcserver-lobby-advancedportals-config
              mountPath: /plugins/AdvancedPortals/portals.yml
              subPath: portals.yml

      volumes:
        # paperのボリューム
        - name: data
          emptyDir: {}

        # configmmapの指定
        - name: mcserver-lobby-config
          configMap:
            name: mc-lobby-configs
        - name: mcserver-lobby-plugin-config
          configMap:
            name: mc-lobby-plugin-configs
        - name: mcserver-lobby-holograms-config
          configMap:
            name: mc-lobby-holograms-configs
        - name: mcserver-lobby-advancedportals-config
          configMap:
            name: mc-lobby-advancedportals-configs
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config

        # initContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: world-download-volume
          emptyDir: {}
        - name: world-edit-download-volume
          emptyDir: {}
        - name: world-guard-download-volume
          emptyDir: {}
        - name: jmx-exporter-download-volume
          emptyDir: {}
