apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-lobby-sv
  name: mc-lobby
  labels:
    app: mc-lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-lobby
  template:
    metadata:
      labels:
        app: mc-lobby
    spec:
      initContainers:
        # lobbyサーバーをgithubに格納されているワールドデータに指定するためのダウンロード及び配置作業
        - name: download-world
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - >
              wget -O /data/world.zip https://github.com/maron-gt123/k8s-setup-for-proxmox/archive/refs/heads/main.zip &&
              unzip -o /data/world.zip -d /data &&
              cp -r /data/k8s-setup-for-proxmox-main/k8s/manifests/apps/minecraft-lobby/world/ /data &&
              rm /data/world.zip &&
              rm -r /data/k8s-setup-for-proxmox-main
          volumeMounts:
            - name: world-download-volume
              mountPath: /data
        # pluginデータのダウンロード及び配置
        - name: plugins-downloader
          image: busybox:1.36.1
          env:
            - name: WORLD_EDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/5507246/download"
            - name: WORLD_GUARD_URL
              value: "https://dev.bukkit.org/projects/worldguard/files/5344377/download"
          volumeMounts:
            - name: world-edit-download-volume
              mountPath: /root/world-edit-download
            - name: world-guard-download-volume
              mountPath: /root/world-guard-download
          command:
            - sh
            - -c
            - >
              wget -O /root/world-edit-download/worldedit-bukkit.jar "${WORLD_EDIT_URL}" &&
              wget -O /root/world-guard-download/worldguard-bukkit.jar "${WORLD_GUARD_URL}"
      containers:
        - image: itzg/minecraft-server:java21
          name: mc-lobby
          env:
            # minecraftのeulaについて「同意」の宣言
            - name: EULA
              value: "TRUE"
            # サーバーのtime設定を日本標準時に
            - name: TZ
              value: Asia/Tokyo
            # 本docer_imageの起動サーバ宣言を指定
            - name: TYPE
              value: PAPER
            # 本docer_imageの起動サーバーverを指定
            - name: VERSION
              value: "1.20.6"
            # rconの設定を「true」に
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              value: "maroncloud"
            # 最小利用メモリ
            - name: INIT_MEMORY
              value: 1G
            # 最大利用メモリ
            - name: MAX_MEMORY
              value: 2G
            # netherの精製か可否
            - name: ALLOW_NETHER
              value: "false"
            # ゲームモードの設定
            - name: DIFFICULTY
              value: peaceful
            # velocity経由でのログインのためfalseに設定
            - name: ONLINE_MODE
              value: "FALSE"
            # worldの精製条件
            - name: LEVEL_TYPE
              value: flat
            # 動物系mobのspown設定
            - name: SPAWN_ANIMALS
              value: "false"
            # 敵対系mobのspown設定
            - name: SPAWN_MONSTERS
              value: "false"
            # npc系mobのspown設定
            - name: SPAWN_NPCS
              value: "false"
            # whitelist設定
            - name: ENABLE_WHITELIST
              value: "true"
            - name: WHITELIST
              valus: maron_12345
            # フルpathのpluginが公開されているものはここで直接ダウンロードし/data/pluginsに格納
            - name: PLUGINS
              # minecraft-prometheus-exporter3.1.0
              # LuckPerms-Bukkit5.4.137
              # Advanced-Portals-0.9.3
              value: >-
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar,
                https://download.luckperms.net/1552/bukkit/loader/LuckPerms-Bukkit-5.4.137.jar,
                https://github.com/sekwah41/Advanced-Portals/releases/download/v0.9.3/Advanced-Portals-0.9.3.jar
            # Spiget API経由でダウンロード可能なpluginは本docer_imageの機能を活用し格納
            - name: SPIGET_RESOURCES  
              # LunaChat
              #   https://www.spigotmc.org/resources/lunachat.82293/
              # DecentHolograms
              #   https://www.spigotmc.org/resources/decentholograms-1-8-1-20-1-papi-support-no-dependencies.96927/
              value: 82293,96927
          ports:
            - name: mc-lobby
              containerPort: 25565
            - name: rcon-lobby
              containerPort: 25575
            - name: mc-metrics
              containerPort: 35353
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            # bukkit configのマウント
            - name: mcserver-lobby-config
              mountPath: /config/bukkit.yml
              subPath: mc-bukkit.yml
            # spigot configのマウント
            - name: mcserver-lobby-config
              mountPath: /config/spigot.yml
              subPath: mc-spigot.yml
            # paper-global configのマウント
            - name: mcserver-lobby-config
              mountPath: /config/paper-global.yml
              subPath: mc-paper-global.yml
            # world-editのマウント
            - name: world-edit-download-volume
              mountPath: /data
            # world-editのマウント
            - name: world-edit-download-volume
              mountPath: /data/plugins/worldedit-bukkit.jar
              subPath: worldedit-bukkit.jar
            # world-guardのマウント
            - name: world-guard-download-volume
              mountPath: /data/plugins/worldguard-bukkit.jar
              subPath: worldguard-bukkit.jar
      volumes:
        - name: mcserver-lobby-config
          configMap:
            name: mc-lobby-configs
        - name: mcserver-lobby-plugin-config
          configMap:
            name:  mc-lobby-plugin-configs
        # worldデータをinitContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: world-download-volume
          emptyDir: {}
        # world-edit.jarをinitContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: world-edit-download-volume
          emptyDir: {}
        # world-guard.jarをinitContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: world-guard-download-volume
          emptyDir: {}
