apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc-lobby-sv
  name: mc-lobby
  labels:
    app: mc-lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-lobby
  template:
    metadata:
      labels:
        app: mc-lobby
    spec:
      initContainers:
        # lobbyサーバーをgithubに格納されているワールドデータに指定するためのダウンロード及び配置作業
        - name: download-world
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - >
              wget -O /data/world.zip https://github.com/maron-gt123/k8s-setup-for-proxmox/archive/refs/heads/main.zip &&
              unzip -o /data/world.zip -d /data &&
              cp -r /data/k8s-setup-for-proxmox-main/k8s/manifests/apps/minecraft-lobby/world/ /data &&
              rm /data/world.zip &&
              rm -r /data/k8s-setup-for-proxmox-main
          volumeMounts:
            - name: world-download-volume
              mountPath: /data
        # pluginデータ及びJMX_exporterのダウンロード及び配置
        - name: plugins-downloader
          image: busybox:1.36.1
          env:
            - name: WORLD_EDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/5507246/download"
            - name: WORLD_GUARD_URL
              value: "https://dev.bukkit.org/projects/worldguard/files/5344377/download"
            - name: JMX_EXPORTER_URL
              value: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar"
          volumeMounts:
            - name: world-edit-download-volume
              mountPath: /root/world-edit-download
            - name: world-guard-download-volume
              mountPath: /root/world-guard-download
            - name: jmx-exporter-download-volume
              mountPath: /root/jmx-exporter-download
          command:
            - sh
            - -c
            - >
              wget -O /root/world-edit-download/worldedit-bukkit.jar "${WORLD_EDIT_URL}" &&
              wget -O /root/world-guard-download/worldguard-bukkit.jar "${WORLD_GUARD_URL}" &&
              wget -O /root/jmx-exporter-download/jmx-exporter-javaagent.jar "${JMX_EXPORTER_URL}"
      containers:
        - image: itzg/minecraft-server:java21
          name: mc-lobby
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: PAPER
            - name: VERSION
              value: "1.20.6"
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              value: "maroncloud"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: ONLINE_MODE
              value: "FALSE"
            - name: LEVEL_TYPE
              value: flat
            - name: SPAWN_ANIMALS
              value: "false"
            - name: SPAWN_MONSTERS
              value: "false"
            - name: SPAWN_NPCS
              value: "false"
            - name: ENABLE_WHITELIST
              value: "true"
            - name: PLUGINS
              # minecraft-prometheus-exporter3.1.0
              # LuckPerms-Bukkit5.4.137
              # Advanced-Portals-0.9.3
              # LunaChat
              # DecentHolograms
              value: >-
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar,
                https://download.luckperms.net/1552/bukkit/loader/LuckPerms-Bukkit-5.4.137.jar,
                https://github.com/sekwah41/Advanced-Portals/releases/download/v0.9.3/Advanced-Portals-0.9.3.jar,
                https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar,
                https://github.com/DecentSoftware-eu/DecentHolograms/releases/download/2.8.9/DecentHolograms-2.8.9.jar
            - name: JVM_OPTS
              value: >-
                -javaagent:/jmx-exporter/jmx-exporter-javaagent.jar=18321:/jmx-exporter/jmx-exporter-config.yaml
            - name: COPY_CONFIG_DEST
              # /config をサーバーディレクトリにコピーするようにする
              # https://github.com/itzg/docker-minecraft-server/tree/9458005b5bd78b8139e13e66c29a449a12dd6218#optional-plugins-mods-and-config-attach-points
              value: /data
          ports:
            - name: mc-lobby
              containerPort: 25565
            - name: rcon-lobby
              containerPort: 25575
            - name: mc-metrics
              containerPort: 35353
            - name: jmx-metrics
              containerPort: 18321
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            # bukkit configのマウント
            - name: mcserver-lobby-config
              mountPath: /config/bukkit.yml
              subPath: mc-bukkit.yml
            # spigot configのマウント
            - name: mcserver-lobby-config
              mountPath: /config/spigot.yml
              subPath: mc-spigot.yml
            # paper-global configのマウント
            - name: mcserver-lobby-config
              mountPath: /config/config/paper-global.yml
              subPath: mc-paper-global.yml
            # whitelist configのマウント
            - name: mcserver-lobby-config
              mountPath: /config/whitelist.json
              subPath: mc-whitelist.json
            # jmx-exporterの設定
            - name: jmx-exporter-download-volume
              mountPath: /jmx-exporter/jmx-exporter-javaagent.jar
              subPath: jmx-exporter-javaagent.jar
            - name: jmx-exporter-config
              mountPath: /jmx-exporter/jmx-exporter-config.yaml
              subPath: jmx-exporter-config.yaml
            # world-editのマウント
            - name: world-edit-download-volume
              mountPath: /data/plugins/worldedit-bukkit.jar
              subPath: worldedit-bukkit.jar
            # world-guardのマウント
            - name: world-guard-download-volume
              mountPath: /data/plugins/worldguard-bukkit.jar
              subPath: worldguard-bukkit.jar
      volumes:
        - name: mcserver-lobby-config
          configMap:
            name: mc-lobby-configs
        - name: mcserver-lobby-plugin-config
          configMap:
            name:  mc-lobby-plugin-configs
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config
        # worldデータをinitContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: world-download-volume
          emptyDir: {}
        # world-edit.jarをinitContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: world-edit-download-volume
          emptyDir: {}
        # world-guard.jarをinitContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: world-guard-download-volume
          emptyDir: {}
        # JMX exporterをinitContainerでダウンロードしてBugneeCordに受け渡すためのvolume
        - name: jmx-exporter-download-volume
          emptyDir: {}
