apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - image: itzg/minecraft-server:java17
          name: minecraft
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: PAPER
            - name: ENABLE_RCON
              value: "true"
            - name: VERSION
              value: "1.19.2"
            - name: DIFFICULTY
              value: peaceful
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              memory: 2G
              cpu: "2"
#          volumeMounts:
#            - name: server-config
#              mountPath: /data/config

      volumes:
        - name: minecraft-storage
          persistentVolumeClaim:
            claimName: minecraft-pvc
        - name: server-config
          configMap:
            name: common-mcserver-configs
