apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: mic
  labels:
    app: mic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mic
    spec:
      containers:
        - image: itzg/minecraft-server:java17
          name: mic
          env:
            - name: TYPE
              value: PAPER
            - name: ENABLE_RCON
              value: "true"
            - name: VERSION
              value: "1.19.2"

            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 2G

            - name: UID
              value: "0"
            - name: GID
              value: "0"
          volumeMounts:
            - name: minecraft-storage
              mountPath: /data
      volumes:
        - name: minecraft-storage
          persistentVolumeClaim:
            claimName: minecraft-pvc
