apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: minecraft-server-lb
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 192.168.15.71
