apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: minecraft-server-lb
  labels:
    app: minecraft
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 53616
    protocol: TCP
    targetPort: minecraft
  selector:
    app: minecraft
  type: LoadBalancer
  loadBalancerIP: 192.168.15.70
