apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # statefulset
  - ./statefulset.yaml
  # service
  - ./service.yaml
  # metrics-service
  - ./mc-metrics-patch.yaml
  # jmx-exporter-config
  - ./jmx-exporter-config.yaml
  # mc-common-plugin-config
  - ./mc-common-plugin-config.yaml
  # luckperms-config
  - ./mc-plugin-luckperms-config.yaml
