apiVersion: v1
kind: Service
metadata:
  namespace: mc-lobby-sv
  name: mc-lobby-service
  labels:
    app: mc-lobby
spec:
  type: ClusterIP
  ports:
  - name: mc-lobby
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc-lobby
