apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        - name: jmx-exporter-downloader
          image: busybox:1.36.1
          env:
            - name: JMX_EXPORTER_URL
              value: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - "sh"
            - "-c"
            - 'wget -O /root/initContainer-download/jmx-exporter-javaagent.jar "${JMX_EXPORTER_URL}"'
        - name: plugins-download
          image: busybox:1.36.1
          env:
            - name: WORLDEDIT_URL
              value: "https://dev.bukkit.org/projects/worldedit/files/5935693/download"
            - name: WORLDGUARD_URL
              value: "https://dev.bukkit.org/projects/worldguard/files/5888870/download"
            - name: SPAWN_URL
              value: "https://cdn.modrinth.com/data/Pw3KRjwE/versions/mgrZ4A8t/Spawn-2.4.1.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/initContainer-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/initContainer-download/Spawn-2.4.1.jar "${SPAWN_URL}"
      containers:
        - image: itzg/minecraft-server:java21
          name: minecraft
          envFrom:
            - configMapRef:
                name: mc-properties-config
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: PAPER
            - name: VERSION
              value: "1.21.3"
            - name: ENABLE_RCON
              value: "true"
            #- name: INIT_MEMORY
            #  value: 1G
            #- name: MAX_MEMORY
            #  value: 2G
            #- name: ALLOW_NETHER
            #  value: "true"
            #- name: DIFFICULTY
            #  value: easy
            - name: ONLINE_MODE
              value: "false"
            #- name: LEVEL_TYPE
            #  value: normal
            #- name: SPAWN_ANIMALS
            #  value: "true"
            #- name: SPAWN_MONSTERS
            #  value: "true"
            #- name: SPAWN_NPCS
            #  value: "true"
            #- name: ENABLE_WHITELIST
            #  value: "false"
            - name: PLUGINS
              # フルpathのpluginが公開されているものはここで直接ダウンロードし/data/pluginsに格納
              # minecraft-prometheus-exporter3.1.0
              # LuckPerms-Bukkit5.4.137
              # Advanced-Portals-0.9.3
              # LunaChat
              # DecentHolograms
              value: >-
                https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar,
                https://download.luckperms.net/1568/bukkit/loader/LuckPerms-Bukkit-5.4.151.jar,
                https://github.com/sekwah41/Advanced-Portals/releases/download/v1.0.0/Advanced-Portals-1.0.0.jar,
                https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar,
                https://github.com/DecentSoftware-eu/DecentHolograms/releases/download/2.8.12/DecentHolograms-2.8.12.jar
            - name: JVM_OPTS
              value: >-
                -javaagent:/jmx-exporter/jmx-exporter-javaagent.jar=18321:/jmx-exporter/jmx-exporter-config.yaml
            # config関連を/configから/dataへmcopy
            - name: COPY_CONFIG_DEST
              value: /data
            - name: REPLACE_ENV_VARIABLE_PREFIX
              value: CFG_
            - name: CFG_LUCKPERMS-SERVER
              value: ""
            - name: RCON_CMDS_STARTUP
              value: |-

          ports:
            - name: mc-service
              containerPort: 25565
            - name: mc-metrics
              containerPort: 9225
            - name: mc-jmx-metrics
              containerPort: 18321
          resources:
            requests:
              memory: 2G
              cpu: "2"
          volumeMounts:
            # world関連の格納先マウント
            - name: data
              mountPath: /data
            # JMX exporter 周りのファイルが入ったボリューム達のマウント設定
            - name: init-download-volume
              mountPath: /jmx-exporter/jmx-exporter-javaagent.jar
              subPath: jmx-exporter-javaagent.jar
            - name: jmx-exporter-config
              mountPath: /jmx-exporter/jmx-exporter-config.yaml
              subPath: jmx-exporter-config.yaml
            # bukkit/spigot/paper-global/whitelist configのマウント
            - name: mc-config
              mountPath: /config/bukkit.yml
              subPath: mc-bukkit.yml
            - name: mc-config
              mountPath: /config/spigot.yml
              subPath: mc-spigot.yml
            - name: mc-config
              mountPath: /config/config/paper-global.yml
              subPath: mc-paper-global.yml
            - name: mc-config
              mountPath: /config/whitelist.json
              subPath: mc-whitelist.json
            # prometeus/LunaChat/AdvancedPortals(common)のマウント
            - name: mc-common-plugin-config
              mountPath: /config/plugins/PrometheusExporter/config.yml
              subPath: prometheusexporter.yml
            - name: mc-common-plugin-config
              mountPath: /config/plugins/LunaChat/config.yml
              subPath: lunachat.yml
            # LuckPermsのマウント
            - name: mc-plugin-luckperms-config
              mountPath: /config/plugins/LuckPerms/config.yml
              subPath: luckperms.yml
            # advancedportalsのマウント
            - name: mc-plugin-advancedportals-config
              mountPath: /config/plugins/AdvancedPortals/config.yml
              subPath: advancedportals-config.yml

      volumes:
        # paperのボリューム
        - name: data
          emptyDir: {}
        # initContainerでダウンロードしてpaperに受け渡すためのvolume
        - name: init-download-volume
          emptyDir: {}
        # jmx-exporter-configの指定
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config
        # configmap格納先 
        - name: mc-config
          configMap:
            name: mc-configs
        # plugin-common-configmap格納先
        - name: mc-common-plugin-config
          configMap:
            name: mc-common-plugin-configs
        # luckperms格納先
        - name: mc-plugin-luckperms-config
          configMap:
            name: mc-plugin-luckperms-configs
        # advancedportals格納先
        - name: mc-plugin-advancedportals-config
          configMap:
            name: mc-plugin-advancedportals-configs
