apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-debug-sv
resources:
  # namespace
  - ./ns-mc-debug-sv.yaml
  # template
  - ../templates/minecraft-server
patches:
  - path: mc-debug-config.yaml
  - target:
      kind: StatefulSet
      name: minecraft
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/11/value
        value: debug-sv
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/11
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/10
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/9
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/8
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/7
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/6
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/5
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/4
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/3
