apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-debug-sv
resources:
  # namespace
  - ./ns-mc-debug-sv.yaml
  # template
  - ../templates/minecraft-server
  # mc-config
  - ./mc-debug-config.yaml
patches:
  - target:
      kind: StatefulSet
      name: minecraft
    patch: |-
      # advancedportalsのマウント
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/9
      # LuckPermsのマウント
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/8
      # prometheusexporter
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/7
      # lunachat
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/6
      # mc-paper-global
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/5
      # mc-spigot
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/4
      # mc-bukkit
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/3
      # mc-plugin-advancedportals
      - op: remove
        path: /spec/template/spec/volumes/6
       # luckperms
      - op: remove
        path: /spec/template/spec/volumes/5
       #  plugin-common-configmap
      - op: remove
        path: /spec/template/spec/volumes/4
       # configmap
      - op: remove
        path: /spec/template/spec/volumes/3
