apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mc-lobby-sv
  name: mc-lobby-configs
data:
  bukkit.yml: |
    settings:
      allow-end: false
      warn-on-overload: true
      permissions-file: permissions.yml
      update-folder: update
      plugin-profiling: false
      connection-throttle: 4000
      query-plugins: true
      deprecated-verbose: default
      shutdown-message: Server closed
      minimum-api: none
      use-map-color-cache: true
    spawn-limits:
      monsters: 70
      animals: 10
      water-animals: 5
      water-ambient: 20
      water-underground-creature: 5
      axolotls: 5
      ambient: 15
    chunk-gc:
      period-in-ticks: 600
    ticks-per:
      animal-spawns: 400
      monster-spawns: 1
      water-spawns: 1
      water-ambient-spawns: 1
      water-underground-creature-spawns: 1
      axolotl-spawns: 1
      ambient-spawns: 1
      autosave: 6000
    aliases: now-in-commands.yml
  whitelist.json: |
    [
      {
        "uuid": "a4ea87de-f923-4889-9bd2-7d4899803d2d",
        "name": "latch1225"
      },
      {
        "uuid": "ebd6ed5c-7a32-49fd-b287-df57f2ffb33b",
        "name": "maron_12345"
      }
    ]  
  paper-global.yml: |
    # This is the global configuration file for Paper.
    # As you can see, there's a lot to configure. Some options may impact gameplay, so use
    # with caution, and make sure you know what each option does before configuring.
    #
    # If you need help with the configuration or have any questions related to Paper,
    # join us in our Discord or check the docs page.
    #
    # The world configuration options have been moved inside
    # their respective world folder. The files are named paper-world.yml
    #
    # Docs: https://docs.papermc.io/
    # Discord: https://discord.gg/papermc
    # Website: https://papermc.io/
    
    _version: 28
    block-updates:
      disable-chorus-plant-updates: false
      disable-mushroom-block-updates: false
      disable-noteblock-updates: false
      disable-tripwire-updates: false
    chunk-loading-advanced:
      auto-config-send-distance: true
      player-max-concurrent-chunk-generates: 0
      player-max-concurrent-chunk-loads: 0
    chunk-loading-basic:
      player-max-chunk-generate-rate: -1.0
      player-max-chunk-load-rate: 100.0
      player-max-chunk-send-rate: 75.0
    chunk-system:
      gen-parallelism: default
      io-threads: -1
      worker-threads: -1
    collisions:
      enable-player-collisions: true
      send-full-pos-for-hard-colliding-entities: true
    commands:
      fix-target-selector-tag-completion: true
      suggest-player-names-when-null-tab-completions: true
      time-command-affects-all-worlds: false
    console:
      enable-brigadier-completions: true
      enable-brigadier-highlighting: true
      has-all-permissions: false
    item-validation:
      book:
        author: 8192
        page: 16384
        title: 8192
      book-size:
        page-max: 2560
        total-multiplier: 0.98
      display-name: 8192
      lore-line: 8192
      resolve-selectors-in-books: false
    logging:
      deobfuscate-stacktraces: true
      log-player-ip-addresses: true
    messages:
      kick:
        authentication-servers-down: <lang:multiplayer.disconnect.authservers_down>
        connection-throttle: Connection throttled! Please wait before reconnecting.
        flying-player: <lang:multiplayer.disconnect.flying>
        flying-vehicle: <lang:multiplayer.disconnect.flying>
      no-permission: <red>I'm sorry, but you do not have permission to perform this command.
        Please contact the server administrators if you believe that this is in error.
      use-display-name-in-quit-message: false
    misc:
      chat-threads:
        chat-executor-core-size: -1
        chat-executor-max-size: -1
      compression-level: default
      fix-entity-position-desync: true
      load-permissions-yml-before-plugins: true
      max-joins-per-tick: 5
      region-file-cache-size: 256
      strict-advancement-dimension-check: false
      use-alternative-luck-formula: false
      use-dimension-type-for-custom-spawners: false
    packet-limiter:
      all-packets:
        action: KICK
        interval: 7.0
        max-packet-rate: 500.0
      kick-message: <red><lang:disconnect.exceeded_packet_rate>
      overrides:
        ServerboundPlaceRecipePacket:
          action: DROP
          interval: 4.0
          max-packet-rate: 5.0
    player-auto-save:
      max-per-tick: -1
      rate: -1
    proxies:
      bungee-cord:
        online-mode: false
      proxy-protocol: false
      velocity:
        enabled: true
        online-mode: true
        secret: gytS9ZohJscB
    scoreboards:
      save-empty-scoreboard-teams: false
      track-plugin-scoreboards: false
    spam-limiter:
      incoming-packet-threshold: 300
      recipe-spam-increment: 1
      recipe-spam-limit: 20
      tab-spam-increment: 1
      tab-spam-limit: 500
    timings:
      enabled: true
      hidden-config-entries:
      - database
      - proxies.velocity.secret
      history-interval: 300
      history-length: 3600
      server-name: Unknown Server
      server-name-privacy: false
      url: https://timings.aikar.co/
      verbose: true
    unsupported-settings:
      allow-grindstone-overstacking: false
      allow-headless-pistons: false
      allow-permanent-block-break-exploits: false
      allow-piston-duplication: false
      compression-format: ZLIB
      perform-username-validation: true
    watchdog:
      early-warning-delay: 10000
      early-warning-every: 5000
  server.properties: |
    #Minecraft server properties
    allow-flight=false
    allow-nether=false
    broadcast-console-to-ops=true
    broadcast-rcon-to-ops=true
    debug=false
    difficulty=peaceful
    enable-command-block=false
    enable-jmx-monitoring=false
    enable-query=false
    enable-rcon=true
    enable-status=true
    enforce-secure-profile=true
    enforce-whitelist=false
    entity-broadcast-range-percentage=100
    force-gamemode=false
    function-permission-level=2
    gamemode=survival
    generate-structures=true
    generator-settings={}
    hardcore=false
    hide-online-players=false
    level-name=world
    level-seed=
    level-type=minecraft\:flat
    max-chained-neighbor-updates=1000000
    max-players=30
    max-tick-time=-1
    max-world-size=500
    motd=A Minecraft Server
    network-compression-threshold=256
    online-mode=false
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    previews-chat=false
    pvp=true
    query.port=25565
    rate-limit=0
    rcon.password=maroncloud
    rcon.port=25575
    require-resource-pack=false
    resource-pack=
    resource-pack-prompt=
    resource-pack-sha1=
    server-ip=
    server-port=25565
    simulation-distance=10
    spawn-animals=false
    spawn-monsters=false
    spawn-npcs=false
    spawn-protection=16
    sync-chunk-writes=true
    text-filtering-config=
    use-native-transport=true
    view-distance=10
    white-list=true
