apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mic-lobby-sv
  name: primary-sv
  labels:
    app: primary-sv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary-sv
  template:
    metadata:
      labels:
        app: primary-sv
    spec:
      initContainers:
        - name: copy-config
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - >
              cp /mnt/config/whitelist.json /app/whitelist.json
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config
            - name: primary-sv-storage
              mountPath: /app
      containers:
        - name: primary-sv
          image: noevidenz/multipaper-master:edge
          env:
            - name: TZ
              value: Asia/Tokyo
          resources:
            requests:
              memory: 2G
              cpu: "2"
          ports:
            - name: multipaper-ex
              containerPort: 25565
            - name: multipaper-int
              containerPort: 35353
          volumeMounts:
            - name: primary-sv-storage
              mountPath: /app
      volumes:
        - name: primary-sv-storage
          persistentVolumeClaim:
            claimName: primary-sv-pvc
        - name: config-volume
          configMap:
            name: multipaper-configs
