apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mic-lobby-sv
  name: primary-sv
  labels:
    app: primary-sv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary-sv
  template:
    metadata:
      labels:
        app: primary-sv
    spec:
      initContainers:
        - name: download-world
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - >
              wget -O /app/world.zip https://github.com/maron-gt123/k8s-setup-for-proxmox/archive/refs/heads/main.zip &&
              unzip /app/world.zip -d /app &&
              mv /app/k8s-setup-for-proxmox-main/k8s/manifests/apps/multipaper-lobby/world/* /app &&
              rm /app/world.zip
          volumeMounts:
            - name: primary-sv-storage
              mountPath: /app
      containers:
        - name: primary-sv
          image: noevidenz/multipaper-master:edge
          env:
            - name: TZ
              value: Asia/Tokyo
          resources:
            requests:
              memory: 2G
              cpu: "2"
          ports:
            - name: multipaper-ex
              containerPort: 25565
            - name: multipaper-int
              containerPort: 35353
          volumeMounts:
            - name: primary-sv-storage
              mountPath: /app
            - name: multipaper-configs
              mountPath: /app/whitelist.json
              subPath: whitelist.json
      volumes:
        - name: primary-sv-storage
          persistentVolumeClaim:
            claimName: primary-sv-pvc
        - name: multipaper-configs
          configMap:
            name: multipaper-configs
