apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.2
    helm:
      values: |-
          nfs:
            server: 192.168.6.140
            path: /kubanetesu-NFS
          storageClass:
            name: nfs-storage
          accessModes: ReadWriteMany
          reclaimPolicy: Retain
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
