apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: default
  source:
    chart: pyroscope
    repoURL: https://pyroscope-io.github.io/helm-chart
    targetRevision: 0.2.92
    helm:
      releaseName: pyroscope
      values: |
        persistence:
          enabled: true
          storageClassName: pyroscope-nsf
          accessModes:
            - ReadWriteOnce
          size: 20Gi
        service:
          type: loadBalancer
          port: 4040
          loadBalancerIP: 192.168.15.62
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
