apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: velocity
    release: prometheus
  name: velocity-metrics
spec:
  endpoints:
    - interval: 30s
      port: jmx-metrics
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: velocity
      role: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: velocity-metrics
  labels:
    app: velocity
    role: metrics
spec:
  type: ClusterIP
  ports:
    - name: jmx-metrics
      port: 18321
      protocol: TCP
      targetPort: jmx-metrics
    - name: metrics
      port: 9225
      protocol: TCP
      targetPort: metrics
  selector:
    app: velocity
