apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ./argocd-server-lb.yaml
  - ./argocd-metrics-path.yaml
patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
        namespace: argocd
      data:
        resource.exclusions: |
          - apiGroups:
              - cilium.io
            kinds:
              - CiliumIdentity
            clusters:
              - "*"
          - apiGroups:
              - example.com
            kinds:
              - ExampleKind
            clusters:
              - "cluster-1"
