apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-music-sv
resources:
  # namespace
  - ./ns-mc-music-sv.yaml
  # template
  - ../templates/minecraft-server
  # holograms
  #- ./

patches:
  - path: music-statefulset.yaml
  - path: mc-music-plugin-advancedportals-configs.yaml
