apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: minecraft-music-server-lb
  labels:
    app: minecraft-music
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: minecraft
  - name: mc-metrics
    port: 9225
    protocol: TCP
    targetPort: mc-metrics
  - name: mc-dynmap
    port: 8123
    protocol: TCP
    targetPort: mc-dynmap
  selector:
    app: minecraft-music
  type: LoadBalancer
  loadBalancerIP: 192.168.15.72
