apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-music-world-pvc
  labels:
    app: mc-music
spec:
  storageClassName: mc-music-world-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
