apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minecraft
  name: minecraft-music-pvc
  labels:
    app: minecraft-music
spec:
  storageClassName: minecraft-music
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
