apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mc-music-sv
  name: mc-music-pv
  labels:
    app: mc-music
spec:
  storageClassName: mc-music
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/minecraft-music/
  persistentVolumeReclaimPolicy: Retain
