apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mc-music-sv
  name: mc-music-pvc
  labels:
    app: mc-music
spec:
  storageClassName: mc-music
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
