apiVersion: v1
kind: Service
metadata:
  namespace: mc-music-sv
  name: mc-music-service
  labels:
    app: mc-music
spec:
  type: ClusterIP
  ports:
  - name: mc-music
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc-music
