apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: palworld
  labels:
    app: palworld-server
  name: palworld-server-datadir
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
