apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: prometheus
  labels:
    app.kubernetes.io/name: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.15.63
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
