apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: prometheus
spec:
  ports:
  - name: http-web
    port: 81
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.15.63
