apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /kubanetesu-NFS/prometheus/
    server: 192.168.6.53
  persistentVolumeReclaimPolicy: Retain
