apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.6.53
    path: /kubanetesu-NFS/prometheus/
  persistentVolumeReclaimPolicy: Retain
