apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: prometheus
  labels:
    app: prometheus
spec:
  storageClassName: "prometheus"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
