apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prometheus
  name: prometheus-pvc
  labels:
    app: prometheus
spec:
  storageClassName: prometheus
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
