kube-prometheus-stack:
  server:
    persistentVolume:
      enabled: true
      storageClass: nfs
      size: 5Gi
      accessModes:
        - ReadWriteOnce
      mountOptions:
        - hard
        - nfsvers=4.1
        - proto=tcp
      existingClaim: ""
      annotations: {}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nsf:
        - server: 192.168.6.53
          paths: /kubanetesu-NFS/prometheus/
