prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: prometheus  # 自身の環境に応じて設定
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 10Gi
