project: default
source:
  repoURL: 'https://github.com/maron-gt123/k8s-setup-for-proxmox.git'
  path: k8s/app/bungeecord
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated: {}
