apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/maron-gt123/k8s-setup-for-proxmox.git
    path: k8s/app/minecraft
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
