apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-proxy
  labels:
    app: minecraft-proxy
  # We wish this deployment to be reloaded
  # when "bungeecord-config" and "bungeecord-plugin-configs" ConfigMap are updated
  annotations:
    configmap.reloader.stakater.com/reload: "bungeecord-config"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: minecraft-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      containers:
        - image: itzg/bungeecord:java17
          name: minecraft-proxy
          env:
            - name: TYPE
              value: WATERFALL
            - name: ENABLE_RCON
              value: "true"

            - name: INIT_MEMORY
              value: 250M
            - name: MAX_MEMORY
              value: 1G
          ports:
            - containerPort: 25577
              name: bungeecord
          volumeMounts:
            - name: bungeecord-config
              mountPath: /config/config.yml
              subPath: config.yml

      volumes:
        - name: minecraft-proxy-storage
          persistentVolumeClaim:
            claimName: minecraft-proxy-pvc
        - name: bungeecord-config
          configMap:
            name: bungeecord-config
