apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: minecraft-proxy
  labels:
    app: minecraft-proxy
spec:
  type: LoadBalancer
  ports:
    - name: bungee
      port: 53616
      protocol: TCP
      targetPort: bungeecord
  selector:
    app: bungeecord
  loadBalancerIP: 192.168.15.70
