apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft-proxy
  labels:
    app: minecraft-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minecraft-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      containers:
        - image: itzg/bungeecord:java17
          name: minecraft-proxy
          env:
            - name: TYPE
              value: WATERFALL
            - name: ENABLE_RCON
              value: "true"


            - name: INIT_MEMORY
              value: 250M
            - name: MAX_MEMORY
              value: 1G
          ports:
            - containerPort: 53616
              name: bungeecord
          volumeMounts:
            - name: minecraft-proxy-storage
              mountPath: /kubanetesu-NFS/bungeecord/
      volumes:
        - name: minecraft-proxy-storage
          persistentVolumeClaim:
            claimName: minecraft-proxy-pvc
