apiVersion: v1
kind: Service
metadata:
  name: bungeecord
  labels:
    app: bungeecord
spec:
  type: LoadBalancer
  ports:
    - name: bungee
      port: 53616
      protocol: TCP
      targetPort: 25577
  selector:
    app: bungeecord
  loadBalancerIP: 192.168.15.70
