apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minecraft
  name: iscsi-15gb-claim
  annotations:
    volume.kubernetes.io/storage-class: "iscsi"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 11Gi
