apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: minecraft
  name: iscsi-15gb
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  iscsi:
    targetPortal: 192.168.6.53:3260
    portals: ['0.0.0.0:3260']
    iqn: iqn.2004-04.com.qnap:ts-253d:iscsi.kubanetesu.4bd441
    lun: 0
    fsType: xfs
    readOnly: false
