apiVersion: v1
kind: Service
metadata:
  name: minecraft-proxy
  labels:
    app: minecraft-proxy
spec:
  type: LoadBalancer
  ports:
    - name: bungee
      port: 53616
      protocol: TCP
      targetPort: 53616
    - name: be
      port: 53616
      protocol: UDP
      targetPort: 53616
  selector:
    app: bungeecord
  loadBalancerIP: 192.168.15.70
cloudinit@onp-k8s-cp-1:/k8s/mic-proxy$
cloudinit@onp-k8s-cp-1:/k8s/mic-proxy$
cloudinit@onp-k8s-cp-1:/k8s/mic-proxy$
cloudinit@onp-k8s-cp-1:/k8s/mic-proxy$ cat nsf-pv-bungeecord.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
#  namespace: minecraft
  name: minecraft-proxy-pv
  labels:
    app: minecraft-proxy
spec:
  storageClassName: minecraft-proxy
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.53
    path: /kubanetesu-NFS/bungeecord/
  persistentVolumeReclaimPolicy: Delete
