apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: minecraft
  name: minecraft-proxy-pv
  labels:
    app: minecraft-proxy
spec:
  storageClassName: minecraft-proxy
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.53
    path: /kubanetesu-NFS
  persistentVolumeReclaimPolicy: Delete
