apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sasa
  name: minecraft-pv
  labels:
    app: minecraft
spec:
  storageClassName: minecraft
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.53
    path: /kubanetesu-NFS/minecraft/
  persistentVolumeReclaimPolicy: Delete
